### PR TITLE
Replace deprecated Class.newInstance()

### LINKED ISSUE #3311: Replace deprecated Class.newInstance()
Replace the deprecated `Class.newInstance()` method with `getDeclaredConstructor().newInstance()`.

`Class.newInstance()` has been deprecated since Java 9 because it propagates exceptions thrown by the nullary constructor, including checked exceptions. The replacement wraps such exceptions in an `InvocationTargetException`.

**Files affected:**
- `microservices/starters/datawave/.../DatawaveMetricsConfig.java`
- `microservices/starters/datawave/.../ProtostuffHttpMessageConverter.java`

Part of #2443

### PR DESCRIPTION
**Pull request by SethSmucker**
## Summary
- Replace deprecated `Class.newInstance()` with `getDeclaredConstructor().newInstance()`
- Update exception handling to use `ReflectiveOperationException` (covers the additional exceptions from the new API)

## Files Changed
- `DatawaveMetricsConfig.java`
- `ProtostuffHttpMessageConverter.java`

Fixes #3311
Part of #2443

### CODE REVIEW

**Comment by foster33** [comment]
There are additional occurrences of `Class.newInstance()` throughout the entire code base outside of just `spring-boot-starter-datawave`. Those should probably be added as well

**Review by foster33 — CHANGES_REQUESTED** [review]
There seems to be 4 more uses of `Class.newInstance()`. I will go ahead and make those changes.

**Review by foster33 — DISMISSED** [review]

File: warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/reduce/AggregatingReducer.java [hunk 1]
```diff
@@ -439,11 +439,12 @@ public CustomColumnToClassMapping(Map<String,Entry<Map<String,String>,String>> c
...
                     Class<? extends Combiner> clazz = Class.forName(className).asSubclass(Combiner.class);
 
-                    agg = clazz.newInstance();
+                    agg = clazz.getDeclaredConstructor().newInstance();
                     // init with a stubbed-out class so that an upcoming call to env.getConfig in Combiner will not throw a NPE
                     agg.init(null, clazzOptions.getKey(), new StubbedIteratorEnvironment());
 
-                } catch (InstantiationException | IllegalAccessException | ClassNotFoundException | IOException e) {
+                } catch (InstantiationException | IllegalAccessException | ClassNotFoundException | IOException | NoSuchMethodException
+                                | java.lang.reflect.InvocationTargetException e) {
```
Comment (apmoriarty) [inline warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/reduce/AggregatingReducer.java]: No need for the fully qualified import. Bad bot.

**Comment by lbschanno** [comment]
One additional usage that needs to be replaced:
- BulkIngestKeyAggregatingReducer (line 66)

**Comment by foster33** [comment]
Seems like the usage that Laura mentioned is still there:

`BulkIngestKeyAggregatingReducer` line 66

**Review by apmoriarty — APPROVED** [review]

**Review by foster33 — APPROVED** [review]

**Review by hlgp — APPROVED** [review]
