### PR TITLE
fixes #750 Re-enable AuditBean in Embedded, Filter out shaded guava c…

### LINKED ISSUE #750: BulkResults (via MapReduce API) broken after Datawave refactoring
Additional jars need to be added to the Map/Reduce job context, some classes need to be excluded, some classes need to be created to support running in a map job.

### PR DESCRIPTION
**Pull request by billoley**
fixes #750 Re-enable AuditBean in Embedded, Filter out shaded guava classes from jboss-client.jar while writing to job distributed cache

### CODE REVIEW

File: web-services/map-reduce/src/main/java/datawave/webservice/mr/configuration/MapReduceJobConfiguration.java [hunk 1]
```diff
@@ -302,6 +316,40 @@ protected void prepareClasspath(String jobId, Job job, Path jobDir) throws Excep
...
+                    for (ZipEntry zipEntry = zipInputStream.getNextEntry(); zipEntry != null; zipEntry = zipInputStream.getNextEntry()) {
+                        boolean include = true;
+                        Iterator<Pattern> patternItr = patterns.iterator();
+                        while (patternItr.hasNext() && include == true) {
+                            Pattern p = patternItr.next();
+                            if (p.matcher(zipEntry.getName()).matches()) {
+                                include = false;
+                            }
+                        }
+                        if (include) {
```
Comment (brianloss) [inline web-services/map-reduce/src/main/java/datawave/webservice/mr/configuration/MapReduceJobConfiguration.java]: Not required, but you can simplify this quite a bit with streams...
```suggestion
                        final String entryName = zipEntry.getName();
                        if (patterns.stream().noneMatch(p -> p.matcher(entryName).matches())) {
```

File: web-services/map-reduce/src/main/java/datawave/webservice/mr/configuration/MapReduceJobConfiguration.java [hunk 2]
```diff
@@ -302,6 +316,40 @@ protected void prepareClasspath(String jobId, Job job, Path jobDir) throws Excep
...
+                            zipOutputStream.putNextEntry(zipEntry);
+                            byte[] buffer = new byte[2048];
+                            int len;
+                            while ((len = zipInputStream.read(buffer)) > 0) {
+                                zipOutputStream.write(buffer, 0, len);
+                            }
```
Comment (brianloss) [inline web-services/map-reduce/src/main/java/datawave/webservice/mr/configuration/MapReduceJobConfiguration.java]: Another way...
```suggestion
                            ByteStreams.copy(zipInputStream, zipOutputStream);
```

Comment (billoley) [reply web-services/map-reduce/src/main/java/datawave/webservice/mr/configuration/MapReduceJobConfiguration.java]: Thanks for the suggestions.  This way is much cleaner.  It took me a while to figure out the Zip(Input/Output)Stream semantics and I didn't circle back to clean it up.

Oh the irony that we are using a guava class in the wildfly jvm to remove the wildfly classes from a shaded jar.  I combined both suggestions and pushed a commit.

Comment (brianloss) [reply web-services/map-reduce/src/main/java/datawave/webservice/mr/configuration/MapReduceJobConfiguration.java]: Figured you'd appreciate that. ;)

File: web-services/map-reduce/src/main/java/datawave/webservice/mr/configuration/MapReduceJobConfiguration.java [hunk 3]
```diff
@@ -284,7 +288,17 @@ protected void prepareClasspath(String jobId, Job job, Path jobDir) throws Excep
         File[] jarFiles = libDir.listFiles(jarFilter);
         if (jarFiles != null) {
             for (File jar : jarFiles) {
-                addSingleFile(jar, new Path(classpath, jar.getName()), jobId, job, fs);
+                // remove guava classes from jboss-client.jar
+                if (jar.getName().equals("jboss-client.jar")) {
+                    List<Pattern> patterns = new ArrayList<>();
```
Comment (ivakegg) [inline web-services/map-reduce/src/main/java/datawave/webservice/mr/configuration/MapReduceJobConfiguration.java]: ugh, but ok for now I guess....

Comment (billoley) [reply web-services/map-reduce/src/main/java/datawave/webservice/mr/configuration/MapReduceJobConfiguration.java]: I know, but the alternative is storing a modified version of that file in our version control.  That's not great either.  The dependency is needed for our MapReduce jobs to run, but because of the inability to order the user classpath to the job we have to eliminate the newer guava classes that are shaded into that jar.  

I considered adding configuration to take care of this (which jar to transfer, which regexes to filter out).  I can do that later.  The java would be cleaner at least.   I ran out of time at the end of the week and this will work for now.
