### PR TITLE
fixes #1779 RemoteQueryMetricService.map using wrong URL, need to set…

### LINKED ISSUE #1779: RemoteQueryMetricService.map using wrong URL, need to set basemaps on remote response
`private static final String MAP_METRIC_SUFFIX = "id/map/%s";`
should be
`private static final String MAP_METRIC_SUFFIX = "id/%s/map";`

Because basemaps in QueryGeometryResponse is declared @XmlTransient (only used in the HTML response)
`    @XmlTransient
    protected String basemaps = null;` 
basemaps are not returned with the JSON when using RemoteQueryMetricService.  QueryMetricsBean should set basemaps on the remote response.

### PR DESCRIPTION
**Pull request by billoley**
RemoteQueryMetricService.map using wrong URL, need to set basemaps on remote response

### CODE REVIEW

File: web-services/query/src/main/java/datawave/webservice/query/metric/QueryMetricsBean.java [hunk 1]
```diff
@@ -74,6 +75,9 @@ public class QueryMetricsBean {
     @Inject
     private QueryGeometryHandler queryGeometryHandler;
     @Inject
+    @ConfigProperty(name = "dw.basemaps", defaultValue = "{}")
```
Comment (keith-ratcliffe) [inline web-services/query/src/main/java/datawave/webservice/query/metric/QueryMetricsBean.java:78]: Do we need to add entries for `dw.basemaps` in `[add|remove]-datawave-configuration.cli` and `default.properties` as we do for others?

Comment (billoley) [reply web-services/query/src/main/java/datawave/webservice/query/metric/QueryMetricsBean.java:78]: It's already in there since it gets injected into SimpleQueryGeometryHandler

**Review by apmoriarty — APPROVED** [review]

**Review by keith-ratcliffe — APPROVED** [review]
