### PR TITLE
fixes #3152: Updated MostRecentUnique feature to handle TLD documents

### LINKED ISSUE #3152: Most Recent Unique feature not working with TLDEventQuery
When documents from the TLDEventQuery come back, then have multiple document ids in the Document and hence an Attributes value.  This fails to be casted to a DocumentKey at line 573 of the UniqueTransform.getDocKeyAttr method.

### PR DESCRIPTION
**Pull request by ivakegg**

### CODE REVIEW

File: warehouse/query-core/src/main/java/datawave/query/transformer/UniqueTransform.java [hunk 1]
```diff
@@ -569,12 +568,25 @@ private static long getTimestamp(Document doc) {
         return getDocKeyAttr(doc).getTimestamp();
     }
 
-    private static DocumentKey getDocKeyAttr(Document doc) {
-        return (DocumentKey) (doc.get(Document.DOCKEY_FIELD_NAME));
+    private static Attribute getDocKeyAttr(Document doc) {
+        Attribute<?> attr = doc.get(Document.DOCKEY_FIELD_NAME);
+        if (attr instanceof Attributes) {
+            // if the attr is an instanceof Attributes, then we need to frind the one that best describes
```
Comment (foster33) [inline warehouse/query-core/src/main/java/datawave/query/transformer/UniqueTransform.java]:
```suggestion
            // if the attr is an instanceof Attributes, then we need to find the one that best describes
```

**Review by hlgp — DISMISSED** [review]

**Review by FineAndDandy — DISMISSED** [review]

File: warehouse/query-core/src/main/java/datawave/query/transformer/UniqueTransform.java [hunk 2]
```diff
@@ -569,12 +568,25 @@ private static long getTimestamp(Document doc) {
         return getDocKeyAttr(doc).getTimestamp();
     }
 
-    private static DocumentKey getDocKeyAttr(Document doc) {
-        return (DocumentKey) (doc.get(Document.DOCKEY_FIELD_NAME));
+    private static Attribute getDocKeyAttr(Document doc) {
```
Comment (apmoriarty) [inline warehouse/query-core/src/main/java/datawave/query/transformer/UniqueTransform.java]: Consider renaming to `getRootDocumentKeyAttr`. 

Add a method comment.

File: warehouse/query-core/src/test/java/datawave/query/transformer/UniqueTransformTest.java [hunk 3]
```diff
@@ -610,11 +610,17 @@ protected class InputDocumentBuilder {
...
             Key key = new Key("shardid", "datatype\u0000" + getUid(), cq, ts);
+            Key key2 = new Key("shardid", "datatype\u0000" + getUid() + ".1", cq, ts);
+            Key key3 = new Key("shardid", "datatype\u0000" + getUid() + ".5", cq, ts);
             this.document = new Document(key, true);
             inputDocuments.add(document);
             this.document.getMetadata().set(key);
             Attribute<?> docKeyAttributes = new DocumentKey(key, true);
+            Attribute<?> docKeyAttributes2 = new DocumentKey(key2, true);
+            Attribute<?> docKeyAttributes3 = new DocumentKey(key3, true);
             this.document.put(Document.DOCKEY_FIELD_NAME, docKeyAttributes);
```
Comment (apmoriarty) [inline warehouse/query-core/src/test/java/datawave/query/transformer/UniqueTransformTest.java:617]: I know from experience that this addition to the test data will exercise the new code that was added, but it would be better to open up the `getDocKey` methods from private to protected and add a test case that exercises TLD and child keys.

**Review by apmoriarty — CHANGES_REQUESTED** [review]
Method docs and a test are still needed. Looks good otherwise.

File: warehouse/query-core/src/main/java/datawave/query/transformer/UniqueTransform.java (hunk 2 above)
Comment (ivakegg) [reply warehouse/query-core/src/main/java/datawave/query/transformer/UniqueTransform.java]: ok

File: warehouse/query-core/src/test/java/datawave/query/transformer/UniqueTransformTest.java (hunk 3 above)
Comment (ivakegg) [reply warehouse/query-core/src/test/java/datawave/query/transformer/UniqueTransformTest.java:617]: done

**Review by apmoriarty — APPROVED** [review]

**Review by d-hwang — APPROVED** [review]
