### PR TITLE
fixes #384: allow multiple close requests

### LINKED ISSUE #384: A close request should not necessarily fail
If a query is closed on a webserver (either manually or automatically), a subsequent close request for that query should not fail.

### PR DESCRIPTION
**Pull request by ivakegg**
Added a cache of closed ids to allow subsequent close requests to succeed

### CODE REVIEW

File: web-services/query/src/main/java/datawave/webservice/query/runner/QueryExecutorBean.java [hunk 1]
```diff
@@ -1956,9 +1960,12 @@ private VoidResponse close(String id, Principal principal) {
                     RunningQuery query = getQueryById(id, principal);
                     close(query);
```
Comment (matthpeterson) [inline web-services/query/src/main/java/datawave/webservice/query/runner/QueryExecutorBean.java]: maybe it would be worth checking the cache before doing any additional work, but it seems either way will work.

Comment (ivakegg) [reply web-services/query/src/main/java/datawave/webservice/query/runner/QueryExecutorBean.java]: I debated that, however there are several steps that occur and I wanted at least an administrator to attempt the close process all the way through in case something did not take.  Also there are some subtle differences between the cancel, close, and remove that in fact I am a little confused about.  This seemed the safest solution.
