### PR TITLE
fixes #567 Add QueryPruningVisitor and ignore _NOFIELD_

### LINKED ISSUE #567: _NOFIELD_ can cause executability to be incorrectly determined

### PR DESCRIPTION
**Pull request by FineAndDandy**

### CODE REVIEW

File: warehouse/query-core/src/test/java/datawave/query/jexl/visitors/QueryPruningVisitorTest.java [hunk 1]
```diff
@@ -0,0 +1,268 @@
...
+import org.apache.commons.jexl2.parser.ParseException;
+import org.junit.Assert;
+import org.junit.Test;
+
+public class QueryPruningVisitorTest {
+    @Test
+    public void falseAndTest() throws ParseException {
+        String query = "FIELD1 == 'x' && _NOFIELD_ == 'y'";
+        ASTJexlScript script = JexlASTHelper.parseJexlQuery(query);
+        Assert.assertEquals(QueryPruningVisitor.getState(script), QueryPruningVisitor.TRUTH_STATE.FALSE);
```
Comment (apmoriarty) [inline warehouse/query-core/src/test/java/datawave/query/jexl/visitors/QueryPruningVisitorTest.java]: Flip the arguments. First is expected, second is the state to be tested.

Comment (apmoriarty) [reply warehouse/query-core/src/test/java/datawave/query/jexl/visitors/QueryPruningVisitorTest.java]: This comment applies generally to this test class.

File: warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPruningVisitor.java [hunk 2]
```diff
@@ -0,0 +1,500 @@
...
+import org.apache.commons.jexl2.parser.SimpleNode;
+
+import java.util.ArrayList;
+import java.util.HashSet;
+import java.util.List;
+import java.util.NoSuchElementException;
+import java.util.Set;
+
+/**
+ * Visitor can be used to identify and prune children of a JexlNode that will always be TRUE or FALSE. Our use of _NOFIELD_
```
Comment (ivakegg) [inline warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPruningVisitor.java]: I think you need to complete the second sentence

File: warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPruningVisitor.java [hunk 3]
```diff
@@ -0,0 +1,500 @@
...
+        return identifyAndReplace(node);
+    }
+    
+    // handle merge ups and replacements
+    
+    @Override
+    public Object visit(ASTNotNode node, Object data) {
+        Set<TRUTH_STATE> states = new HashSet<>();
+        for (int i = 0; i < node.jjtGetNumChildren(); i++) {
+            states.add((TRUTH_STATE) (node.jjtGetChild(i).jjtAccept(this, data)));
```
Comment (ivakegg) [inline warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPruningVisitor.java]: I really hope there is only one child here.....

File: warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPruningVisitor.java [hunk 4]
```diff
@@ -0,0 +1,500 @@
...
+        }
+    }
+    
+    // deal with wrappers
+    @Override
+    public Object visit(ASTJexlScript node, Object data) {
+        // attempt to reduce
+        Set<TRUTH_STATE> states = new HashSet<>();
+        for (int i = 0; i < node.jjtGetNumChildren(); i++) {
+            states.add((TRUTH_STATE) (node.jjtGetChild(i).jjtAccept(this, data)));
```
Comment (ivakegg) [inline warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPruningVisitor.java]: I really hope there is only one child here....

File: warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPruningVisitor.java [hunk 5]
```diff
@@ -0,0 +1,500 @@
...
+        } else {
+            return TRUTH_STATE.UNKNOWN;
+        }
+    }
+    
+    @Override
+    public Object visit(ASTReference node, Object data) {
+        Set<TRUTH_STATE> states = new HashSet<>();
+        for (int i = 0; i < node.jjtGetNumChildren(); i++) {
+            states.add((TRUTH_STATE) (node.jjtGetChild(i).jjtAccept(this, data)));
```
Comment (ivakegg) [inline warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPruningVisitor.java]: should only be one child.  Lets put an assert everywhere to ensure we only have one child where appropriate.  Then we will not need to create a new HashSet except for OR and AND nodes.

File: warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPruningVisitor.java [hunk 6]
```diff
@@ -0,0 +1,500 @@
...
+        } else {
+            return TRUTH_STATE.UNKNOWN;
+        }
+    }
+    
+    @Override
+    public Object visit(ASTReferenceExpression node, Object data) {
+        Set<TRUTH_STATE> states = new HashSet<>();
+        for (int i = 0; i < node.jjtGetNumChildren(); i++) {
+            states.add((TRUTH_STATE) (node.jjtGetChild(i).jjtAccept(this, data)));
```
Comment (ivakegg) [inline warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPruningVisitor.java]: one child

File: warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPruningVisitor.java [hunk 7]
```diff
@@ -0,0 +1,500 @@
...
+    }
+    
+    @Override
+    public Object visit(ASTForeachStatement node, Object data) {
+        return TRUTH_STATE.UNKNOWN;
+    }
+    
+    @Override
+    public Object visit(ASTAssignment node, Object data) {
+        return TRUTH_STATE.UNKNOWN;
```
Comment (ivakegg) [inline warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPruningVisitor.java]: TRUE

File: warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPruningVisitor.java (hunk 5 above)
Comment (FineAndDandy) [reply warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPruningVisitor.java]: agree

File: warehouse/query-core/src/main/java/datawave/query/jexl/visitors/ExecutableDeterminationVisitor.java [hunk 8]
```diff
@@ -338,7 +339,9 @@ else if (states.contains(STATE.PARTIAL)) {
     @Override
     public Object visit(ASTEQNode node, Object data) {
         STATE state;
-        if (isUnOrNoFielded(node)) {
+        if (isNoFieldOnly(node)) {
+            state = STATE.IGNORABLE;
+        } else if (isUnOrNoFielded(node)) {
```
Comment (ivakegg) [inline warehouse/query-core/src/main/java/datawave/query/jexl/visitors/ExecutableDeterminationVisitor.java]: Should we create a isUnFielded(node) method?

File: warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPruningVisitor.java [hunk 9]
```diff
@@ -0,0 +1,483 @@
...
+    }
+    
+    @Override
+    public Object visit(ASTOrNode node, Object data) {
+        // grab the node string before recursion so the original is intact
+        String originalString = JexlStringBuildingVisitor.buildQuery(node);
+        
+        Set<TRUTH_STATE> states = new HashSet<>();
+        for (int i = 0; i < node.jjtGetNumChildren(); i++) {
+            states.add((TRUTH_STATE) (node.jjtGetChild(i).jjtAccept(this, data)));
```
Comment (ivakegg) [inline warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPruningVisitor.java]: as soon as you see a true, replaceAndAssign and return true

File: warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPruningVisitor.java [hunk 10]
```diff
@@ -0,0 +1,483 @@
...
+    }
+    
+    @Override
+    public Object visit(ASTAndNode node, Object data) {
+        // grab the node string before recursion so the original is intact
+        String originalString = JexlStringBuildingVisitor.buildQuery(node);
+        
+        Set<TRUTH_STATE> states = new HashSet<>();
+        for (int i = 0; i < node.jjtGetNumChildren(); i++) {
+            states.add((TRUTH_STATE) (node.jjtGetChild(i).jjtAccept(this, data)));
```
Comment (ivakegg) [inline warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPruningVisitor.java]: as with the OrNode, we can short circuit if you find a false.

File: warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPruningVisitor.java [hunk 11]
```diff
@@ -0,0 +1,489 @@
...
+            return TRUTH_STATE.TRUE;
+        } else {
+            return TRUTH_STATE.UNKNOWN;
+        }
+    }
+    
+    @Override
+    public Object visit(ASTOrNode node, Object data) {
+        // grab the node string before recursion so the original is intact
+        String originalString = JexlStringBuildingVisitor.buildQuery(node);
```
Comment (drewfarris) [inline warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPruningVisitor.java]: It's too bad that we can't somehow amortize the cost of capturing the `originalString` - I suspect is is expensive, and we may end up doing it in cases where we don't need to -- on a recursive basis no less.

File: warehouse/query-core/src/test/java/datawave/query/jexl/visitors/QueryPruningVisitorTest.java [hunk 12]
```diff
@@ -0,0 +1,291 @@
...
+        
+        ASTJexlScript script = JexlASTHelper.parseJexlQuery(query);
+        JexlNode reduced = QueryPruningVisitor.reduce(script);
+        
+        Assert.assertEquals("(((pruned = '(_NOFIELD_ == \\'x\\' || _NOFIELD_ == \\'y\\') && _NOFIELD_ == \\'z\\'') && false)) || FIELD2 == 'z'",
+                        JexlStringBuildingVisitor.buildQuery(reduced));
+    }
+    
+    @Test
+    public void deeplyNestedBranchRewriteTest() throws ParseException {
```
Comment (drewfarris) [inline warehouse/query-core/src/test/java/datawave/query/jexl/visitors/QueryPruningVisitorTest.java]: It would be cool to write a test where we have nested pruned subtrees, if I'm thinking about this correctly, we are traversing the tree depth first here, so it would be possible to prine a deeply nested range than then end up pruning a parent range (that included the low-level pruned range) as well. Does that work? Are we doing extra work in that case?

File: warehouse/query-core/src/test/java/datawave/query/jexl/visitors/QueryPruningVisitorTest.java [hunk 13]
```diff
@@ -0,0 +1,291 @@
...
+    }
+    
+    @Test
+    public void functionTest() throws ParseException {
+        String query = "filter:isNull(FIELD)";
+        ASTJexlScript script = JexlASTHelper.parseJexlQuery(query);
+        Assert.assertEquals(QueryPruningVisitor.TRUTH_STATE.UNKNOWN, QueryPruningVisitor.getState(script));
+    }
+    
+    @Test
```
Comment (drewfarris) [inline warehouse/query-core/src/test/java/datawave/query/jexl/visitors/QueryPruningVisitorTest.java]: Consider a bounded range test? A un-indexed field test?

File: warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPruningVisitor.java [hunk 14]
```diff
@@ -0,0 +1,489 @@
...
+import java.util.NoSuchElementException;
+import java.util.Set;
+
+/**
+ * Visitor can be used to identify and prune children of a JexlNode that will always be TRUE or FALSE. When present, _NOFIELD_ indicates that a criteria can
+ * never be fulfilled. Using this visitor two questions can be answered about any JexlNode. What is the JexlNode's current state? And what does the JexlNode's
+ * tree look like if we reduce it based on everything we know to be TRUE/FALSE about the tree?
+ */
+public class QueryPruningVisitor extends BaseVisitor {
+    public enum TRUTH_STATE {
```
[the remark this answers is not in the document]
Comment (FineAndDandy) [reply warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPruningVisitor.java]: fixed

File: warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPruningVisitor.java [hunk 15]
```diff
@@ -0,0 +1,489 @@
...
+        UNKNOWN, TRUE, FALSE
+    }
+    
+    /**
+     * Given a JexlNode, determine if any children or even the node itself can be replaced by a TrueNode or FalseNode, For any rewritten sub-trees, create an
+     * AND node which combines an assignment showing the section of the pruned tree, and the replacement ASTTrue/ASTFalse result of the prune
+     *
```
[the remark this answers is not in the document]
Comment (FineAndDandy) [reply warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPruningVisitor.java]: yes, it is only useful for debugging, I will add this comment and add a flag to enable/disable this and associated code for building in case the cost is high

File: warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPruningVisitor.java [hunk 16]
```diff
@@ -0,0 +1,489 @@
...
+     * @param node
+     *            non-null JexlNode
+     * @return TRUE if evaluation would always return true, FALSE if it will always return false, otherwise UNKNOWN
+     */
+    public static TRUTH_STATE getState(JexlNode node) {
+        QueryPruningVisitor visitor = new QueryPruningVisitor(false);
+        return (TRUTH_STATE) node.jjtAccept(visitor, null);
+    }
+    
+    private boolean rewrite;
```
[the remark this answers is not in the document]
Comment (FineAndDandy) [reply warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPruningVisitor.java]: fixed

File: warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPruningVisitor.java [hunk 17]
```diff
@@ -0,0 +1,489 @@
...
+    /**
+     * Given a JexlNode, determine if any children or even the node itself can be replaced by a TrueNode or FalseNode, For any rewritten sub-trees, create an
+     * AND node which combines an assignment showing the section of the pruned tree, and the replacement ASTTrue/ASTFalse result of the prune
+     * 
+     * @param node
+     *            a non-null query node
+     * @return a rewritten query tree for node
+     */
+    public static JexlNode reduce(JexlNode node) {
+        QueryPruningVisitor visitor = new QueryPruningVisitor(true);
```
[the remark this answers is not in the document]
Comment (FineAndDandy) [reply warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPruningVisitor.java]: The QueryPruningVisitor(false) is used for getState().

File: warehouse/query-core/src/test/java/datawave/query/jexl/visitors/QueryPruningVisitorTest.java (hunk 12 above)
Comment (FineAndDandy) [reply warehouse/query-core/src/test/java/datawave/query/jexl/visitors/QueryPruningVisitorTest.java]: this is exactly that test

File: warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPruningVisitor.java (hunk 11 above)
Comment (FineAndDandy) [reply warehouse/query-core/src/main/java/datawave/query/jexl/visitors/QueryPruningVisitor.java]: We use JexlStringBuildingVisitor liberally throughout the planner code. If it has a major performance problem we should consider fixing that directly. I have updated visit(And/Or node) to only do this step if debug pruning is requested, which will be a configurable option

File: warehouse/query-core/src/test/java/datawave/query/jexl/visitors/QueryPruningVisitorTest.java (hunk 13 above)
Comment (FineAndDandy) [reply warehouse/query-core/src/test/java/datawave/query/jexl/visitors/QueryPruningVisitorTest.java]: This class (QueryPruningVisitor) doesn't know the difference between indexed/unindexed, it is either a _NOFIELD_ or not. Since a bounded range is really a concept instead of a structural construct I'm not sure that has a place in this class either.

Comment (FineAndDandy) [reply warehouse/query-core/src/test/java/datawave/query/jexl/visitors/QueryPruningVisitorTest.java]: I think we have some integration tests that exercise bounded ranges, but I will need to try to confirm that.

File: warehouse/query-core/src/main/java/datawave/query/jexl/visitors/ExecutableDeterminationVisitor.java [hunk 18]
```diff
@@ -536,6 +562,8 @@ public Object visit(ASTGENode node, Object data) {
         // results.
         if (isWithinBoundedRange(node)) {
```
[the remark this answers is not in the document]
Comment (FineAndDandy) [reply warehouse/query-core/src/main/java/datawave/query/jexl/visitors/ExecutableDeterminationVisitor.java]: are there any tests for ```isWithinBoundedRange``` or ```isNonEvent```

[the remark this answers is not in the document]
Comment (FineAndDandy) [reply warehouse/query-core/src/main/java/datawave/query/jexl/visitors/ExecutableDeterminationVisitor.java]: good catch
