### PR TITLE
FederatedQueryPlanner.getSubQueryDateRanges can return an illegal range and is skipping some time periods

### LINKED ISSUE #2679: FederatedQueryPlanner.getSubQueryDateRanges can return an illegal range and is skipping some time periods
Because the index holes are all time midnight, when the final index hole is on the same day as the query endDate but the query endDate is not midnight, the FederatedQueryPlanner is returning a Pair<Date,Date> where the beginDate > endDate

The current logic is also uses oneDayBefore and oneDayAfter in places where oneMsBefore and oneMsAfter are required.  This is causing whole days to be missed when generating subRanges to cover a query date range.

The oneDayBefore and oneDayAfter logic is also causing small periods on the edge of the subRanges to violate the purpose of the method -- that all sub ranges contain all dates with no index holes or all dates with index holes.

More robust testing should be added to prevent regression

### PR DESCRIPTION
**Pull request by billoley**
FederatedQueryPlanner.getSubQueryDateRanges can return an illegal range and is skipping some time periods (#2679)

Because the index holes are all time midnight, when the final index hole is on the same day as the query endDate but the query endDate is not midnight, the FederatedQueryPlanner is returning a Pair<Date,Date> where the beginDate > endDate

The current logic is also uses oneDayBefore and oneDayAfter in places where oneMsBefore and oneMsAfter are required. This is causing whole days to be missed when generating subRanges to cover a query date range.

The oneDayBefore and oneDayAfter logic is also causing small periods on the edge of the subRanges to violate the purpose of the method -- that all sub ranges contain all dates with no index holes or all dates with index holes.

In FederatedQueryPlanner, usages of Calendar were moved to local variables rather than a class variable to avoid the possibility of thread un-safe access.

Added more robust testing to verify fixes and prevent regression

### CODE REVIEW

File: warehouse/query-core/src/main/java/datawave/query/planner/FederatedQueryPlanner.java [hunk 1]
```diff
@@ -482,79 +479,110 @@ private SortedSet<Pair<Date,Date>> getSubQueryDateRanges(ShardQueryConfiguration
...
             // Otherwise, get the valid date ranges. First, Merge any overlaps.
             SortedSet<Pair<Date,Date>> mergedHoles = mergeRanges(relevantHoles);
+            // Adjust the index holes so that they span from 00:00:00.000 on the first day to 23:59:59.999 on the last day
+            mergedHoles = spanEntireDays(mergedHoles);
             Iterator<Pair<Date,Date>> it = mergedHoles.iterator();
 
-            // If the start of the first hole occurs after the configured start date, add a range spanning from the start date to one day before the start
-            // of the first hole.
+            // If the start of the first index hole occurs after the configured start date, add a range spanning from
+            // the beginDate to one day before the start of the first index hole.
```
Comment (ivakegg) [inline warehouse/query-core/src/main/java/datawave/query/planner/FederatedQueryPlanner.java]: Should this be "one ms before the start of the first index hole" ?

**Review by ivakegg — DISMISSED** [review]

**Review by apmoriarty — DISMISSED** [review]

File: warehouse/query-core/src/main/java/datawave/query/planner/FederatedQueryPlanner.java (hunk 1 above)
Comment (billoley) [reply warehouse/query-core/src/main/java/datawave/query/planner/FederatedQueryPlanner.java]: Good catch.  Thanks.

**Review by apmoriarty — APPROVED** [review]

**Review by ivakegg — APPROVED** [review]

**Comment by billoley** [comment]
Tested fix by generating metadata i column index hole at the end of the query range.  Before fix - illegal range where end > start.  After fix - correctly generate sub-ranges with no exception
