### PR TITLE
Fix ScoredPhrase Bug

### LINKED ISSUE #2441: ContentFunctionsDescriptor fails to parse field from scored functions
The ContentFunctionsDescriptor will fail to parse the field from a scored phrase when calling `fieldsAndTerms`

For example: 

Given a function like `content:scoredPhrase(FIELD, -1.5, termOffsetMap, 'foo', 'bar')` the call to fieldsAndTerms should return `{FIELD}, {foo, bar}`, but it will return an empty field set.

Given a function like `content:scoredPhrase((FIELD_A || FIELD_B), -1.5, termOffsetMap, 'foo', 'bar')` the call to fieldsAndTerms should return `{FIELD_A, FIELD_B}, {foo, bar}`, but it will return an empty field set.

### PR DESCRIPTION
**Pull request by apmoriarty**
Fixes https://github.com/NationalSecurityAgency/datawave/issues/2441

- added a test suite for ContentFunctionsDescriptor
- corrected how fields are parsed from a scored function when calling `fieldsAndTerms`

### CODE REVIEW

**Review by ivakegg — DISMISSED** [review]

File: warehouse/query-core/src/main/java/datawave/query/jexl/functions/ContentFunctionsDescriptor.java [hunk 1]
```diff
@@ -300,36 +300,31 @@ public Set<String>[] fieldsAndTerms(Set<String> termFrequencyFields, Set<String>
...
-                            }
-
-                            fields = JexlASTHelper.getIdentifierNames(firstArg);
-                            termOffsetMap = args.next();
+                        if (arg instanceof ASTIdentifier) {
+                            // single field case
+                            fields = Collections.singleton(String.valueOf(JexlASTHelper.getIdentifier(arg)));
                         } else {
-                            termOffsetMap = firstArg;
+                            // multi field case
```
Comment (drewfarris) [inline warehouse/query-core/src/main/java/datawave/query/jexl/functions/ContentFunctionsDescriptor.java:315]: it might be helpful to add an "e.g.," here and for the single field case above, such as:

```
// multi field case, e.g., content:scoredPhrase((FIELD_A || FIELD_B), -1.5, termOffsetMap, 'foo', 'bar')
```

Not critical b/c there are examples in the unit test, but it makes the code a bit more readable.

File: warehouse/query-core/src/main/java/datawave/query/jexl/functions/ContentFunctionsDescriptor.java [hunk 2]
```diff
@@ -300,36 +300,31 @@ public Set<String>[] fieldsAndTerms(Set<String> termFrequencyFields, Set<String>
...
+                            if (!identifiers.isEmpty()) {
+                                fields = identifiers;
+
+                                if (oredFields != null && arg instanceof ASTAndNode) {
+                                    oredFields.setValue(false);
+                                }
+                            }
                         }
+
+                        // skip score
```
Comment (drewfarris) [inline warehouse/query-core/src/main/java/datawave/query/jexl/functions/ContentFunctionsDescriptor.java]: It would be nice to explain why - the code did this previously...

```
// max score not needed for fields and terms
```

**Review by drewfarris — DISMISSED** [review]
It would be nice to add some additional commentary in the comments, but fundamentally this code looks ok.

For future work, it would be nice to consider restructuring the code to avoid a bunch of nested if/else statements. I'm curious how sonar would rate the cyclomatic complexity of this class.

File: warehouse/query-core/src/main/java/datawave/query/jexl/functions/ContentFunctionsDescriptor.java (hunk 1 above)
Comment (apmoriarty) [reply warehouse/query-core/src/main/java/datawave/query/jexl/functions/ContentFunctionsDescriptor.java:315]: I can absolutely do that

**Comment by apmoriarty** [comment]
> It would be nice to add some additional commentary in the comments, but fundamentally this code looks ok.
> 
> For future work, it would be nice to consider restructuring the code to avoid a bunch of nested if/else statements. I'm curious how sonar would rate the cyclomatic complexity of this class.

I originally wanted to break apart that method but decided not to for the sake of keeping the change set small. Since you've asked, I'm more than happy to split out the scored phrase logic into it's own method. Sonar Lint shows the method complexity at 100 -- far too much.

**Comment by apmoriarty** [comment]
> > It would be nice to add some additional commentary in the comments, but fundamentally this code looks ok.
> > For future work, it would be nice to consider restructuring the code to avoid a bunch of nested if/else statements. I'm curious how sonar would rate the cyclomatic complexity of this class.
> 
> I originally wanted to break apart that method but decided not to for the sake of keeping the change set small. Since you've asked, I'm more than happy to split out the scored phrase logic into it's own method. Sonar Lint shows the method complexity at 100 -- far too much.

I took a look at this and to do it right would require a massive expansion of scope. Wrote https://github.com/NationalSecurityAgency/datawave/issues/2456 to track that.

**Review by alerman — APPROVED** [review]

**Comment by keith-ratcliffe** [comment]
Synced w/integration just to get the Docker file fixes for the `quickstart-build-and-test` failure.

**Review by keith-ratcliffe — APPROVED** [review]
