### PR TITLE
fix build warning messages

### LINKED ISSUE #2261: Fix build warnings
There are a lot of build warnings.
Some are pretty straight forward to fix - this ticket will handle those.  A few will require more refactoring or major changes, and will not be included.

### PR DESCRIPTION
**Pull request by cogross**
clears up a number of simple warnings that occur during the build.
(another ticket will cover more of the complex ones that would need a bit of refactoring)

### CODE REVIEW

File: web-services/cached-results/src/main/java/datawave/webservice/results/cached/CachedResultsBean.java [hunk 1]
```diff
@@ -203,7 +203,7 @@ public class CachedResultsBean {
     private CreatedQueryLogicCacheBean qlCache;
 
     @Inject
-    private QueryPredictor predictor;
+    private QueryPredictor<?> predictor;
```
Comment (keith-ratcliffe) [inline web-services/cached-results/src/main/java/datawave/webservice/results/cached/CachedResultsBean.java]: Unclear to me why, but this change appears to be breaking the webservice deployment, causing Weld/CDI to throw `WELD-001408: Unsatisfied dependencies for type QueryPredictor<?> ...` error when trying to inject an instance

File: warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/MultiRFileOutputFormatter.java [hunk 2]
```diff
@@ -145,7 +145,7 @@ public static void setCompressionTableDisallowList(Configuration conf, Set<Strin
     protected static Set<String> getCompressionTableDisallowList(Configuration conf) {
         String tableListString = conf.get(COMPRESSION_DISALLOWLIST);
         if (tableListString == null) {
-            return Collections.EMPTY_SET;
+            return new HashSet<>();
```
Comment (keith-ratcliffe) [inline warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/MultiRFileOutputFormatter.java]: Wouldn't `Collections.emptySet()` resolve the warning and still preserve immutability?

File: warehouse/ingest-json/src/main/java/datawave/ingest/json/config/helper/JsonDataTypeHelper.java [hunk 3]
```diff
@@ -73,13 +73,13 @@ public JsonObjectFlattener newFlattener() {
         } else if (null != this.getFieldAllowlist()) {
             allowlistFields = this.getFieldAllowlist();
         } else {
-            allowlistFields = Collections.EMPTY_SET;
+            allowlistFields = new HashSet<>();
```
Comment (keith-ratcliffe) [inline warehouse/ingest-json/src/main/java/datawave/ingest/json/config/helper/JsonDataTypeHelper.java]: Same as above

File: warehouse/ingest-json/src/main/java/datawave/ingest/json/config/helper/JsonDataTypeHelper.java [hunk 4]
```diff
@@ -73,13 +73,13 @@ public JsonObjectFlattener newFlattener() {
...
         }
 
         if (null != this.getFieldDisallowlist()) {
             disallowlistFields = this.getFieldDisallowlist();
         } else {
-            disallowlistFields = Collections.EMPTY_SET;
+            disallowlistFields = new HashSet<>();
```
Comment (keith-ratcliffe) [inline warehouse/ingest-json/src/main/java/datawave/ingest/json/config/helper/JsonDataTypeHelper.java]: Same as above

**Review by keith-ratcliffe — CHANGES_REQUESTED** [review]

File: web-services/cached-results/src/main/java/datawave/webservice/results/cached/CachedResultsBean.java (hunk 1 above)
Comment (cogross) [reply web-services/cached-results/src/main/java/datawave/webservice/results/cached/CachedResultsBean.java]: Yeah -- just removed it and got it to run.

File: warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/MultiRFileOutputFormatter.java (hunk 2 above)
Comment (cogross) [reply warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/MultiRFileOutputFormatter.java]: Yep.  Changing all 3, resolving as I do it.

**Review by keith-ratcliffe — DISMISSED** [review]

**Review by avgAGB — DISMISSED** [review]

**Review by mineralntl — DISMISSED** [review]

**Review by MiguelRicardos — DISMISSED** [review]

File: warehouse/core/src/main/java/datawave/data/hash/UID.java [hunk 5]
```diff
@@ -43,6 +43,8 @@ public abstract class UID implements Comparable<UID>, Comparator<UID>, Writable,
 
     private static final Logger LOGGER = Logger.getLogger(UID.class);
 
+    private static final long serialVersionUID = 0L;
```
Comment (ivakegg) [inline warehouse/core/src/main/java/datawave/data/hash/UID.java]: should we be computing a more reasonable serial version UID ?  Same comment for everywhere else we use 0L

Comment (cogross) [reply warehouse/core/src/main/java/datawave/data/hash/UID.java]: sure!  fixed *all* the 0L, 1L, 2L, etc.

**Review by avgAGB — DISMISSED** [review]

**Review by avgAGB — DISMISSED** [review]

**Review by alerman — DISMISSED** [review]

File: warehouse/age-off/src/test/java/datawave/iterators/filter/ConfigurableAgeOffFilterTest.java [hunk 6]
```diff
@@ -143,24 +142,24 @@ public void testAcceptKeyValue_TtlSet() throws Exception {
...
-        assertThat(filter.accept(getKey("bar", daysAgo(7)), VALUE), is(true));
-        assertThat(filter.accept(getKey("foo", daysAgo(8)), VALUE), is(true));
+        assertEquals(filter.accept(getKey("bar", daysAgo(7)), VALUE), true);
+        assertEquals(filter.accept(getKey("foo", daysAgo(8)), VALUE), true);
         // this is really old and matches so should not be accepted
-        assertThat(filter.accept(getKey("foo", daysAgo(365)), VALUE), is(false));
+        assertEquals(filter.accept(getKey("foo", daysAgo(365)), VALUE), false);
         // this is really old and matches, but has a future age off date, so should be accepted
-        assertThat(filter.accept(getKey("foo", compositeTS), VALUE), is(true));
+        assertEquals(filter.accept(getKey("foo", compositeTS), VALUE), true);
```
Comment (jalphonso) [inline warehouse/age-off/src/test/java/datawave/iterators/filter/ConfigurableAgeOffFilterTest.java]: should probably use `assertTrue` or `assertFalse` where appropriate instead of assertEquals

**Review by jalphonso — DISMISSED** [review]

File: warehouse/age-off/src/test/java/datawave/iterators/filter/ConfigurableAgeOffFilterTest.java (hunk 6 above)
Comment (cogross) [reply warehouse/age-off/src/test/java/datawave/iterators/filter/ConfigurableAgeOffFilterTest.java]: Done.

**Review by jalphonso — DISMISSED** [review]

**Review by alerman — DISMISSED** [review]

File: core/map-reduce/src/main/java/datawave/core/mapreduce/bulkresults/map/BulkResultsFileOutputMapper.java [hunk 7]
```diff
@@ -100,7 +100,7 @@ protected void map(Key key, Value value, org.apache.hadoop.mapreduce.Mapper<Key,
         entries.put(key, value);
         for (Entry<Key,Value> entry : entries.entrySet()) {
             try {
-                Object o = t.transform(entry);
+                Object o = t.transform(entry.getKey());
```
Comment (ddanielr) [inline core/map-reduce/src/main/java/datawave/core/mapreduce/bulkresults/map/BulkResultsFileOutputMapper.java]: Note: Transform behavior is now using just the key value vs the original key & value.

File: warehouse/age-off/src/test/java/datawave/iterators/filter/ConfigurableAgeOffFilterTest.java [hunk 8]
```diff
@@ -1,9 +1,6 @@
 package datawave.iterators.filter;
 
-import static org.hamcrest.CoreMatchers.is;
-import static org.hamcrest.MatcherAssert.assertThat;
-import static org.junit.Assert.assertNotNull;
-import static org.junit.Assert.assertSame;
+import static org.junit.Assert.*;
```
Comment (ddanielr) [inline warehouse/age-off/src/test/java/datawave/iterators/filter/ConfigurableAgeOffFilterTest.java]: Avoid wildcard imports. 
```suggestion
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertTrue;
```

File: warehouse/ingest-core/src/main/java/datawave/ingest/data/tokenize/TokenizationHelper.java [hunk 9]
```diff
@@ -6,6 +6,7 @@
 import org.apache.log4j.Logger;
 import org.apache.lucene.analysis.Analyzer;
 import org.apache.lucene.analysis.CharArraySet;
+import org.apache.lucene.analysis.en.EnglishAnalyzer;
```
Comment (ddanielr) [inline warehouse/ingest-core/src/main/java/datawave/ingest/data/tokenize/TokenizationHelper.java]: Note: Imported class is different than original class used.

**Review by ddanielr — COMMENTED** [review]
Two code changes seemed to have possible behavior changes. Everything else seems fine. 

There are some wildcard imports that should probably be removed.

File: warehouse/age-off/src/test/java/datawave/iterators/filter/ConfigurableAgeOffFilterTest.java (hunk 8 above)
Comment (cogross) [reply warehouse/age-off/src/test/java/datawave/iterators/filter/ConfigurableAgeOffFilterTest.java]: IntelliJ being "helpful" there....

File: warehouse/ingest-core/src/main/java/datawave/ingest/data/tokenize/TokenizationHelper.java (hunk 9 above)
Comment (cogross) [reply warehouse/ingest-core/src/main/java/datawave/ingest/data/tokenize/TokenizationHelper.java]: fixed

File: core/map-reduce/src/main/java/datawave/core/mapreduce/bulkresults/map/BulkResultsFileOutputMapper.java (hunk 7 above)
Comment (cogross) [reply core/map-reduce/src/main/java/datawave/core/mapreduce/bulkresults/map/BulkResultsFileOutputMapper.java]: fixed

**Comment by cogross** [comment]
> There are some wildcard imports that should probably be removed.
One was already in (fixed it), the other was intellij being helpful, also fixed.

**Review by jalphonso — DISMISSED** [review]

**Review by ddanielr — DISMISSED** [review]

**Review by alerman — DISMISSED** [review]

**Comment by alerman** [comment]
Rebased so checks would run.

**Review by jalphonso — APPROVED** [review]

**Review by jalphonso — APPROVED** [review]

**Review by ddanielr — APPROVED** [review]

**Review by jalphonso — APPROVED** [review]
