### PR TITLE
Fixes #1506 - AbstractUIDBuilder config no longer dependent on logger…

### LINKED ISSUE #1506: Bug: Proper configuration of UIDBuilder is contingent on log4j logger status
[AbstractUIDBuilder](https://github.com/NationalSecurityAgency/datawave/blob/integration/warehouse/core/src/main/java/datawave/data/hash/AbstractUIDBuilder.java#L112) can create an invalid uidType configuration when debug logging is disabled

Steps to reproduce:
Disable debug logging on AbstractUIDBuilder's logger and run UIDTest. Observe failing unit test, `testConfigurationViaBuilder`

### PR DESCRIPTION
**Pull request by keith-ratcliffe**

### CODE REVIEW

**Review by billoley — DISMISSED** [review]

File: warehouse/core/src/main/java/datawave/data/hash/AbstractUIDBuilder.java [hunk 1]
```diff
@@ -109,7 +109,7 @@ private void configure(final Configuration config, final Map<String,Option> opti
                     LOGGER.debug(message);
                 }
                 config.setInt(CONFIG_MACHINE_ID_KEY, machineId);
-            } else if (LOGGER.isDebugEnabled()) {
+            } else {
                 final String message = "Unable to set configuration to use " + SnowflakeUIDBuilder.class.getSimpleName() + " based on UID type " + uidType
                                 + " with machine ID " + machineId;
                 LOGGER.warn(message);
```
Comment (jwomeara) [inline warehouse/core/src/main/java/datawave/data/hash/AbstractUIDBuilder.java]:
```suggestion
            } else {
                if (LOGGER.isDebugEnabled()) {
                    final String message = "Unable to set configuration to use " + SnowflakeUIDBuilder.class.getSimpleName() + " based on UID type " + uidType
                                    + " with machine ID " + machineId;
                    LOGGER.warn(message);
                }
```

Comment (jwomeara) [reply warehouse/core/src/main/java/datawave/data/hash/AbstractUIDBuilder.java]: Is this not more in line with the original intent of the code?

**Review by hlgp — DISMISSED** [review]

**Review by alerman — DISMISSED** [review]

**Review by apmoriarty — DISMISSED** [review]
