### PR TITLE
#1275: Fix for GROUPBY with multivalued fields where not all fields have every sub-field populated.

### LINKED ISSUE #1275: GroupBy needs to handle multivalued fields from atoms where not every field is populated in every atom.

### PR DESCRIPTION
**Pull request by friedlou**
Fix #1275

### CODE REVIEW

File: warehouse/query-core/src/main/java/datawave/query/transformer/GroupingTransform.java [hunk 1]
```diff
@@ -437,18 +437,19 @@ private void getListKeyCounts(Entry<Key,Document> entry) {
         int longest = this.longestValueList(fieldToFieldWithContextMap);
         for (int i = 0; i < longest; i++) {
             Collection<GroupingTypeAttribute<?>> fieldCollection = new HashSet<>();
-            String currentGroupingContext = "";
```
Comment (ejrgilbert) [inline warehouse/query-core/src/main/java/datawave/query/transformer/GroupingTransform.java:440]: I'd pull this `currentGroupingContext` var into a method since you're replicating what is done in [line 330](https://github.com/NationalSecurityAgency/datawave/blob/8ba03b751d64f3545ed89fe520d074a2bc2ef836/warehouse/query-core/src/main/java/datawave/query/transformer/GroupingTransform.java#L330)

File: warehouse/query-core/src/main/java/datawave/query/transformer/GroupingTransform.java [hunk 2]
```diff
@@ -437,18 +437,19 @@ private void getListKeyCounts(Entry<Key,Document> entry) {
...
+            String currentGroupingContext = Integer.toHexString(i).toUpperCase();
+            ;
```
Comment (ejrgilbert) [inline warehouse/query-core/src/main/java/datawave/query/transformer/GroupingTransform.java]: floating semicolon

File: warehouse/query-core/src/main/java/datawave/query/transformer/GroupingTransform.java (hunk 1 above)
Comment (friedlou) [reply warehouse/query-core/src/main/java/datawave/query/transformer/GroupingTransform.java:440]: Done in the latest commit.

File: warehouse/query-core/src/main/java/datawave/query/transformer/GroupingTransform.java (hunk 2 above)
Comment (friedlou) [reply warehouse/query-core/src/main/java/datawave/query/transformer/GroupingTransform.java]: Removed in the latest commit.

**Review by matthpeterson — APPROVED** [review]
Looks good.
