### PR TITLE
Fixes #257: UnsupportedOperationException on unfielded SlopQueryNode

### LINKED ISSUE #257: UnsupportedOperationException in tokenized query on unfielded SlopQueryNode
A query like `"portable format"~3` that is tokenized will cause the following exception to be thrown:

```
datawave.query.language.parser.ParseException: java.lang.UnsupportedOperationException: datawave.query.language.parser.jexl.JexlWithinNode found as a child of a SlopQueryNode -- not implemented

	at datawave.query.language.parser.jexl.LuceneToJexlQueryParser.convertToJexlNode(LuceneToJexlQueryParser.java:98)
	at datawave.query.language.parser.jexl.LuceneToJexlQueryParser.parse(LuceneToJexlQueryParser.java:57)
	at datawave.query.language.parser.jexl.TestLuceneToJexlQueryParser.parseQuery(TestLuceneToJexlQueryParser.java:374)
	at datawave.query.language.parser.jexl.TestLuceneToJexlQueryParser.testTokenizeUnfieldedWithin(TestLuceneToJexlQueryParser.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.UnsupportedOperationException: datawave.query.language.parser.jexl.JexlWithinNode found as a child of a SlopQueryNode -- not implemented
	at datawave.query.language.builder.jexl.SlopQueryNodeBuilder.build(SlopQueryNodeBuilder.java:57)
	at datawave.query.language.builder.jexl.SlopQueryNodeBuilder.build(SlopQueryNodeBuilder.java:36)
	at org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.processNode(QueryTreeBuilder.java:186)
	at org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.process(QueryTreeBuilder.java:125)
	at org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.build(QueryTreeBuilder.java:218)
	at datawave.query.language.builder.jexl.JexlTreeBuilder.build(JexlTreeBuilder.java:79)
	at datawave.query.language.builder.jexl.JexlTreeBuilder.build(JexlTreeBuilder.java:48)
	at datawave.query.language.parser.jexl.LuceneToJexlQueryParser.convertToJexlNode(LuceneToJexlQueryParser.java:96)
	... 26 more
```

### PR DESCRIPTION
**Pull request by drewfarris**
- Reworks CustomAnalyzerQueryNodeProcessor to handle the various
   cases we will encounter when tokenizing QueryNodes: single terms,
   phrases and phrases with slop.
 - Adds unit tests to cover these cases
 - Removes stray System.out from RegexpQueryNodeBuilder
 - Adjusts some configuration parameter names for CustomAnalyzerQueryNodeProcessor
   for clarity.

### CODE REVIEW

File: warehouse/query-core/src/main/java/datawave/query/language/processor/lucene/CustomAnalyzerQueryNodeProcessor.java [hunk 1]
```diff
@@ -130,48 +170,74 @@ public QueryNode process(QueryNode queryTree) throws QueryNodeException {
...
+                    
+                    return node;
                 }
-                
-                return fieldNode;
             }
             
             if ((tokenizedFields.contains(field.toUpperCase()) || (unfieldedTokenized && field.isEmpty()))) {
                 node = tokenizeNode(node, text, field);
+
```
Comment (drewfarris) [inline warehouse/query-core/src/main/java/datawave/query/language/processor/lucene/CustomAnalyzerQueryNodeProcessor.java]: remove stray whitespace

File: warehouse/query-core/src/main/java/datawave/query/language/processor/lucene/CustomAnalyzerQueryNodeProcessor.java [hunk 2]
```diff
@@ -292,10 +386,28 @@ private final String toStringEscaped(UnescapedCharSequence unescaped) {
     }
     
     @Override
-    protected QueryNode preProcessNode(QueryNode node) throws QueryNodeException {
+    protected QueryNode postProcessNode(QueryNode node) throws QueryNodeException {
```
Comment (drewfarris) [inline warehouse/query-core/src/main/java/datawave/query/language/processor/lucene/CustomAnalyzerQueryNodeProcessor.java]: remove this all, it's no longer needed.

File: warehouse/query-core/src/main/java/datawave/query/language/processor/lucene/CustomAnalyzerQueryNodeProcessor.java [hunk 3]
```diff
@@ -68,15 +84,47 @@
...
+     * special fields, don't tokenize these if <code>unfieldedTokenized</code> is true, and remove them from the query node so downstream processors treat the
+     * node as unfielded.
+     */
     private Set<String> skipTokenizeUnfieldedFields = new HashSet<>();
-    private boolean tokensAsPhrase = false;
     
+    /** treat tokenized test as a phrase (as opposed to a phrase-with-slop) */
+    private boolean useSlopForTokenizedTerms = true;
+    
+    CustomAnalyzerQueryNodeProcessor() {}
```
Comment (brianloss) [inline warehouse/query-core/src/main/java/datawave/query/language/processor/lucene/CustomAnalyzerQueryNodeProcessor.java]: Don't see any other constructors. Is there a reason for adding this one?

**Comment by drewfarris** [comment]
There's at least one place where `tokesAsPhrase` is referred to in the comments after the PR is applied. I'll fix this.

File: warehouse/query-core/src/main/java/datawave/query/language/processor/lucene/CustomAnalyzerQueryNodeProcessor.java [hunk 4]
```diff
@@ -252,6 +359,11 @@ protected QueryNode tokenizeNode(QueryNode node, String text, String field) thro
                     }
                 }
```
Comment (ivakegg) [inline warehouse/query-core/src/main/java/datawave/query/language/processor/lucene/CustomAnalyzerQueryNodeProcessor.java]: put a comment here as to the state at this point in the code: namely n's text is different than ours and hence we will create an or node with the two children....
