### PR TITLE
Fix bug when delayed index streams are added to the query plan multiple times

### LINKED ISSUE #1643: Intersection will duplicate delayed index streams
When one or more index streams are delayed and at least three other index streams are active, the delayed terms are distributed multiple times. Fix this.

### PR DESCRIPTION
**Pull request by apmoriarty**
Fixes https://github.com/NationalSecurityAgency/datawave/issues/1643

- queries should no longer duplicate subtrees when delayed terms exist
- document range query plans now have delayed terms propagated correctly
- fix rare case that would skip shards for queries like `A && (B or delayed(C))` by adding an `IndexStreamComparator` to ensure that VARIABLE children are advanced *after* a context has been found
- RangeStream correctly handles a top level union with a VARIALBE context
- Intersection and Union report more accurate stream contexts
- IndexStreams support nexting with context
- ConcurrentScannerInitializer builds index streams with correct context

### CODE REVIEW

File: warehouse/query-core/src/main/java/datawave/query/index/lookup/IndexStream.java [hunk 1]
```diff
@@ -87,4 +80,13 @@ enum StreamContext {
      * @return the top shard after seeking, or null if no more values exist
      */
     String seek(String seekShard);
+    
+    /**
+     * In certain cases a next call must be made within a context
```
Comment (FineAndDandy) [inline warehouse/query-core/src/main/java/datawave/query/index/lookup/IndexStream.java]: make this explicit

File: warehouse/query-core/src/main/java/datawave/query/index/lookup/IndexStreamComparator.java [hunk 2]
```diff
@@ -0,0 +1,90 @@
...
+public class IndexStreamComparator implements Comparator<IndexStream> {
+    
+    @Override
+    public int compare(IndexStream left, IndexStream right) {
+        int leftId = id(left);
+        int rightId = id(right);
+        
+        int result = Integer.compare(leftId, rightId);
+        if (result == 0) {
+            return 1;
```
Comment (FineAndDandy) [inline warehouse/query-core/src/main/java/datawave/query/index/lookup/IndexStreamComparator.java]: explain this?

File: warehouse/query-core/src/main/java/datawave/query/index/lookup/Union.java [hunk 3]
```diff
@@ -43,110 +44,102 @@ public Union(Iterable<? extends IndexStream> children) {
...
+                    case VARIABLE:
                     case EXCEEDED_VALUE_THRESHOLD:
-                    case EXCEEDED_TERM_THRESHOLD:
-                        if (log.isTraceEnabled())
-                            log.trace("Adding current node to stream");
-                        /*
-                         * Helpful for debugging
-                         */
+                        // index streams with data are always added
+                        this.children.add(stream);
```
Comment (FineAndDandy) [inline warehouse/query-core/src/main/java/datawave/query/index/lookup/Union.java:67]: is it intended to add this back into the same children set that is being looped over?

File: warehouse/query-core/src/main/java/datawave/query/index/lookup/Union.java [hunk 4]
```diff
@@ -43,110 +44,102 @@ public Union(Iterable<? extends IndexStream> children) {
...
+            switch (stream.context()) {
+                case NO_OP:
+                case ABSENT:
+                    // these index streams are dropped from the union
+                    continue;
+                case UNINDEXED:
+                    // a non-indexed field present in a top level union results in a non-executable query
+                    delayedFromUnindexed = true;
+                    delayedNodes.add(stream.currentNode());
+                    continue;
```
Comment (FineAndDandy) [inline warehouse/query-core/src/main/java/datawave/query/index/lookup/Union.java]: these two lines can be removed

File: warehouse/query-core/src/main/java/datawave/query/index/lookup/Union.java [hunk 5]
```diff
@@ -208,7 +228,7 @@ private Tuple2<String,IndexInfo> advanceQueue() {
             
             IndexStream itr = children.poll();
             
-            pointers = pointers.union(itr.peek().second(), Lists.newArrayList(delayedNodes.getNodes()));
+            pointers = pointers.union(itr.peek().second(), Collections.emptyList());
```
Comment (FineAndDandy) [inline warehouse/query-core/src/main/java/datawave/query/index/lookup/Union.java:230]: why are the delayed nodes dropped here?

File: warehouse/query-core/src/main/java/datawave/query/index/lookup/Intersection.java [hunk 6]
```diff
@@ -219,6 +237,18 @@ public Tuple2<String,IndexInfo> next() {
...
+    /**
+     * This is a no-op for the Intersection class. Delegates to {@link #next()}
+     *
+     * @param context
+     *            a context
+     * @return the result of calling {@link #next()}
+     */
+    @Override
+    public Tuple2<String,IndexInfo> next(String context) {
+        return next();
```
Comment (FineAndDandy) [inline warehouse/query-core/src/main/java/datawave/query/index/lookup/Intersection.java:255]: couldn't context be used to potentially skip forward?

File: warehouse/query-core/src/test/java/datawave/query/index/lookup/IndexStreamComparatorTest.java [hunk 7]
```diff
@@ -0,0 +1,225 @@
...
+import static datawave.query.index.lookup.IndexStream.StreamContext.EXCEEDED_VALUE_THRESHOLD;
+import static datawave.query.index.lookup.IndexStream.StreamContext.IGNORED;
+import static datawave.query.index.lookup.IndexStream.StreamContext.PRESENT;
+import static datawave.query.index.lookup.IndexStream.StreamContext.UNINDEXED;
+import static datawave.query.index.lookup.IndexStream.StreamContext.UNKNOWN_FIELD;
+import static org.junit.Assert.assertEquals;
+import static org.junit.Assert.assertFalse;
+import static org.junit.Assert.assertTrue;
+
+public class IndexStreamComparatorTest {
```
Comment (FineAndDandy) [inline warehouse/query-core/src/test/java/datawave/query/index/lookup/IndexStreamComparatorTest.java:31]: great tests

File: warehouse/query-core/src/test/java/datawave/query/index/lookup/RangeStreamQueryTest.java [hunk 8]
```diff
@@ -0,0 +1,435 @@
...
+import static org.junit.Assert.assertTrue;
+import static org.junit.Assert.fail;
+
+/**
+ * Integration test for asserting correct query plans coming off the RangeStream
+ * <p>
+ * Underlying index streams are assumed to have data based on the field
+ */
+@Category(IntegrationTest.class)
+public class RangeStreamQueryTest {
```
Comment (FineAndDandy) [inline warehouse/query-core/src/test/java/datawave/query/index/lookup/RangeStreamQueryTest.java:59]: more great tests

File: warehouse/query-core/src/test/java/datawave/query/index/lookup/RangeStreamQueryTest.java [hunk 9]
```diff
@@ -0,0 +1,435 @@
...
+        
+        // Run a standard limited-scanner range stream.
+        count++;
+        rangeStream = new RangeStream(config, new ScannerFactory(config.getConnector(), 1), helper);
+        rangeStream.setLimitScanners(true);
+        
+        script = JexlASTHelper.parseAndFlattenJexlQuery(query);
+        CloseableIterable<QueryPlan> queryPlans = rangeStream.streamPlans(script);
+        
+        // call to 'iterator()' may modify the stream context
```
Comment (FineAndDandy) [inline warehouse/query-core/src/test/java/datawave/query/index/lookup/RangeStreamQueryTest.java]: may?

**Review by FineAndDandy — CHANGES_REQUESTED** [review]
looks really good, especially the tests. I just have a few questions.

File: warehouse/query-core/src/main/java/datawave/query/index/lookup/IndexStream.java (hunk 1 above)
Comment (apmoriarty) [reply warehouse/query-core/src/main/java/datawave/query/index/lookup/IndexStream.java]: Explained in next commit

File: warehouse/query-core/src/main/java/datawave/query/index/lookup/IndexStreamComparator.java (hunk 2 above)
Comment (apmoriarty) [reply warehouse/query-core/src/main/java/datawave/query/index/lookup/IndexStreamComparator.java]: Explained in next commit.

File: warehouse/query-core/src/main/java/datawave/query/index/lookup/Union.java (hunk 3 above)
Comment (apmoriarty) [reply warehouse/query-core/src/main/java/datawave/query/index/lookup/Union.java:67]: It's not the same collection. The incoming collection of index stream is called `children`, which is different from the class-level priority queue called `children`. I'm renaming the provided collection of index streams to `streams`

File: warehouse/query-core/src/main/java/datawave/query/index/lookup/Union.java (hunk 5 above)
Comment (apmoriarty) [reply warehouse/query-core/src/main/java/datawave/query/index/lookup/Union.java:230]: The delayed nodes are added at the very end. Otherwise the delayed terms are distributed into the union once per active index stream. I'll make a comment to that effect.

File: warehouse/query-core/src/main/java/datawave/query/index/lookup/Union.java (hunk 4 above)
Comment (apmoriarty) [reply warehouse/query-core/src/main/java/datawave/query/index/lookup/Union.java]: removed in next commit

File: warehouse/query-core/src/test/java/datawave/query/index/lookup/RangeStreamQueryTest.java (hunk 9 above)
Comment (apmoriarty) [reply warehouse/query-core/src/test/java/datawave/query/index/lookup/RangeStreamQueryTest.java]: Clarified in next commit.

File: warehouse/query-core/src/main/java/datawave/query/index/lookup/Intersection.java (hunk 6 above)
Comment (apmoriarty) [reply warehouse/query-core/src/main/java/datawave/query/index/lookup/Intersection.java:255]: I'll take a look doing this.

Comment (apmoriarty) [reply warehouse/query-core/src/main/java/datawave/query/index/lookup/Intersection.java:255]: Added in latest commit

**Review by FineAndDandy — APPROVED** [review]

**Review by avgAGB — APPROVED** [review]
