### PR TITLE
Correct DROP state for normalization bug.

### LINKED ISSUE #2266: DROP state for normalization failure
DROP state for normalization was originally intended to prevent the errant value from being indexed. However, we are dropping the field from the event altogether which is not correct.

### PR DESCRIPTION
**Pull request by rdhayes68**

### CODE REVIEW

File: warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/handler/shard/ShardedDataTypeHandler.java [hunk 1]
```diff
@@ -1019,50 +1019,52 @@ protected Multimap<BulkIngestKey,Value> createShardFieldIndexColumn(RawRecordCon
...
+                    Text maskedColq = new Text(normalizedMaskedValue);
+                    TextUtil.textAppend(maskedColq, event.getDataType().outputName(), replaceMalformedUTF8);
+                    TextUtil.textAppend(maskedColq, event.getId().toString(), replaceMalformedUTF8);
+
+                    // Put masked colq with masked visibility
+                    Key k = createKey(shardId, colf, maskedColq, maskedVisibility, event.getDate(), deleteMode);
+                    BulkIngestKey bKey = new BulkIngestKey(this.getShardTableName(), k);
+                    values.put(bKey, value);
+                }
+            } else if (!StringUtils.isEmpty(fieldValue)) {
```
Comment (mineralntl) [inline warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/handler/shard/ShardedDataTypeHandler.java:1051]: Super nit-picky but consistency with negating .isEmpty() or using .isNotEmpty() - functionally doesn't really matter but just something I noticed since the above was changed to use .isNotEmpty()

File: warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/handler/shard/ShardedDataTypeHandler.java [hunk 2]
```diff
@@ -1097,51 +1099,53 @@ protected void createShardFieldIndexColumn(RawRecordContainer event, Multimap<Bu
...
```
Comment (mineralntl) [inline warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/handler/shard/ShardedDataTypeHandler.java:1129]: Same comment about consistency - again, doesn't really matter just something I noticed

Comment (rdhayes68) [reply warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/handler/shard/ShardedDataTypeHandler.java:1129]: Thanks Miner.

File: warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/handler/shard/ShardedDataTypeHandler.java (hunk 1 above)
Comment (rdhayes68) [reply warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/handler/shard/ShardedDataTypeHandler.java:1051]: Thanks.

**Comment by hlgp** [comment]
looks good so far. will take a closer look next week

File: warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/handler/shard/ShardedDataTypeHandler.java [hunk 3]
```diff
@@ -1019,50 +1019,52 @@ protected Multimap<BulkIngestKey,Value> createShardFieldIndexColumn(RawRecordCon
...
             }
 
-            // We need to use the normalized masked values
-            final String normalizedMaskedValue = helper.getNormalizedMaskedValue(fieldName);
-            if (!StringUtils.isEmpty(normalizedMaskedValue)) {
-                Text maskedColq = new Text(normalizedMaskedValue);
-                TextUtil.textAppend(maskedColq, event.getDataType().outputName(), replaceMalformedUTF8);
-                TextUtil.textAppend(maskedColq, event.getId().toString(), replaceMalformedUTF8);
+            if (null != maskedFieldHelper && maskedFieldHelper.contains(fieldName)) {
+                if (!StringUtils.isEmpty(fieldValue)) {
```
Comment (hlgp) [inline warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/handler/shard/ShardedDataTypeHandler.java]: Do we still need this with the check above?

File: warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/handler/shard/ShardedDataTypeHandler.java [hunk 4]
```diff
@@ -1097,51 +1099,53 @@ protected void createShardFieldIndexColumn(RawRecordContainer event, Multimap<Bu
...
+
+            if (value == null) {
+                value = NULL_VALUE;
+            }
 
-        if (value == null) {
-            value = NULL_VALUE;
-        }
+            if (null != maskedFieldHelper && maskedFieldHelper.contains(fieldName)) {
+                if (!StringUtils.isEmpty(fieldValue)) {
```
Comment (hlgp) [inline warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/handler/shard/ShardedDataTypeHandler.java]: same comment

File: warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/handler/shard/ShardedDataTypeHandler.java (hunk 3 above)
Comment (rdhayes68) [reply warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/handler/shard/ShardedDataTypeHandler.java]: No we do not.

**Review by hgklohr — APPROVED** [review]

**Review by hlgp — APPROVED** [review]
