### PR TITLE
fixed python2 and 3 compatibility issues w docker-quickstart scripts

### LINKED ISSUE #2611: Some Quickstart scripts don't work with Docker-Quickstart
Within the datawave-quickstart, there are some scripts that use Python. When run using the Docker-quickstart, those scripts do not work. One that I found to not work properly was `ingest-tv-shows.sh` (might be others).

**_Quickstart scripts that use python:_**
- `query.sh`
- `tvmaze-api-query.sh`

Docker-quickstart will need Python to be installed. In addition, some of the code within those bash scripts might need to be updated to ensure compatibility for Python 2.X and Python 3.X.

### PR DESCRIPTION
**Pull request by skyler-kv**
Fixed the scripts within docker-quickstart that used Python, `query.sh` and `tvmaze-api-query.sh` were affected and now support Python2 and Python3. `ingest-tv-shows.sh` now works correctly. Added Python3 to `Dockerfile`

Fixes #2611

### CODE REVIEW

File: contrib/datawave-quickstart/bin/query.sh [hunk 1]
```diff
@@ -131,21 +131,32 @@ function setQueryIdFromResponse() {
...
-        if [ "${exitStatus}" != "0" ] ; then
-           printRawResponse "${1}"
-           warn "Python encountered error. Printed response without formatting"
-           echo
+    PY_CMD='"from __future__ import print_function; import sys,json; data=json.loads(sys.stdin.read()); print(json.dumps(data, indent=2, sort_keys=True)"'
+        PY3=$(which python3 2>/dev/null)
+        PY2=$(which python2 2>/dev/null)
+        if [ -n "${PY3}" ] ; then
+                echo "${1}" | "${PY3}" -c "${PY_CMD}"
+            local exitStatus=$?
```
Comment (foster33) [inline contrib/datawave-quickstart/bin/query.sh]: There are some places throughout your changes where lines are indented incorrectly. Here in this example, you can see the extra indentation in front of the `PY3` and `PY2` variables all the way down to the closing of the if statement (`fi`). We should probably change that, and make sure each line is properly indented.

File: contrib/datawave-quickstart/bin/query.sh [hunk 2]
```diff
@@ -131,21 +131,32 @@ function setQueryIdFromResponse() {
...
-        echo "${1}" | ${PY} -c 'from __future__ import print_function;import sys,json;data=json.loads(sys.stdin.read()); print(json.dumps(data, indent=2, sort_keys=True))'
-        local exitStatus=$?
-        echo
-        if [ "${exitStatus}" != "0" ] ; then
-           printRawResponse "${1}"
-           warn "Python encountered error. Printed response without formatting"
-           echo
+    PY_CMD='"from __future__ import print_function; import sys,json; data=json.loads(sys.stdin.read()); print(json.dumps(data, indent=2, sort_keys=True)"'
+        PY3=$(which python3 2>/dev/null)
+        PY2=$(which python2 2>/dev/null)
```
Comment (foster33) [inline contrib/datawave-quickstart/bin/query.sh]: I would be interested to see if you could find a way to simplify this a little more. This approach adds some repeating code to handle the two cases. Maybe you could try to consolidate them into one variable, so you do not have to repeat any code.

File: contrib/datawave-quickstart/bin/services/datawave/ingest-examples/tvmaze-api-query.sh [hunk 3]
```diff
@@ -38,10 +38,17 @@ TVMAZE_RESPONSE_STATUS=$( echo ${CURL_RESPONSE} | tr -d '\n' | sed -e 's/.*HTTP_
...
+  if [ "${PRETTY}" == true ] ; then
+    if [ -d "${PY3}" ]; then
+      echo "${TVMAZE_RESPONSE_BODY}" | "${PY3}" ${PY_CMD}
+    elif [ -d "${PY2}" ]; then
+      echo "${TVMAZE_RESPONSE_BODY}" | "${PY2}" ${PY_CMD}
+    fi
+  else
     echo "${TVMAZE_RESPONSE_BODY}"
-fi
+  fi
```
Comment (foster33) [inline contrib/datawave-quickstart/bin/services/datawave/ingest-examples/tvmaze-api-query.sh]: Here is another example of the incorrect indentation.

**Review by foster33 — APPROVED** [review]
LGTM. Tested the changes.

**Review by keith-ratcliffe — DISMISSED** [review]
lgtm

File: contrib/datawave-quickstart/bin/query.sh [hunk 4]
```diff
@@ -131,21 +131,8 @@ function setQueryIdFromResponse() {
...
-           printRawResponse "${1}"
-           warn "Python encountered error. Printed response without formatting"
-           echo
-        fi
-    else
-        printRawResponse "${1}"
-        warn "Couldn't find python in your environment. Json response was printed without formatting"
-        echo
-    fi
+    PY_CMD='"from __future__ import print_function; import sys,json; data=json.loads(sys.stdin.read()); print(json.dumps(data, indent=2, sort_keys=True)"'
```
Comment (foster33) [inline contrib/datawave-quickstart/bin/query.sh]: This seems to differ from the `PY_CMD` variable in `tvmaze-api-query.sh`. We probably want to remove the double quotes and include the missing parenthesis.
```suggestion
    PY_CMD='from __future__ import print_function; import sys,json; data=json.loads(sys.stdin.read()); print(json.dumps(data, indent=2, sort_keys=True))'
```

**Review by foster33 — CHANGES_REQUESTED** [review]
See latest comment

**Review by foster33 — APPROVED** [review]

**Review by apmoriarty — APPROVED** [review]
