### PR TITLE
Re: #887 - Avoid NPEs for EvaluationPhaseFilterFunctions.timeFunction()

### LINKED ISSUE #887: Exceptions thrown when evaluating functions are silently swallowed
DatawaveInterpreter uses strict=false during evaluation which results in no error being thrown if an exception is encountered during a method invocation (any function).  There are multiple places in the interpreter code which test strict before throwing exceptions.  Specifically the invocationFailed() is responsible for deciding to throw exceptions from inside called functions.  This may result in missed hits.

If a function in the query throws an exception, it should error the query.  Note that setting strict=false may be required for other reasons (to be verified).

### PR DESCRIPTION
**Pull request by codebyneesh**
If null field values are passed into timeFunction(), that a NPE is not thrown, and an empty matches set is returned. getMaxTime(), getMinTime(), getMaxValue(), and getMinValue() are private to ensure null values cannot be passed to them.

Resolves #887

### CODE REVIEW

**Review by ivakegg — APPROVED** [review]

File: warehouse/query-core/src/main/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctions.java [hunk 1]
```diff
@@ -1592,7 +1596,7 @@ static long getNextTime(long time, int granularity) {
      * @throws ParseException
      *             if the value failed to be parsed using the supplied format
      */
-    protected static long getTime(Object value, DateFormat format) throws ParseException {
+    static long getTime(Object value, DateFormat format) throws ParseException {
```
Comment (apmoriarty) [inline warehouse/query-core/src/main/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctions.java]: It's a nitpick but I would prefer these be `public static...`

**Review by apmoriarty — DISMISSED** [review]

File: warehouse/query-core/src/main/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctions.java (hunk 1 above)
Comment (ivakegg) [reply warehouse/query-core/src/main/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctions.java]: Create pr/1368 branch in datawave repo to allow integration testing to start.

Comment (ivakegg) [inline warehouse/query-core/src/main/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctions.java]: I finally got to getting this built with our internal project.  This failed because this function is no longer available by an extending class.  This needs to be protected or public, but not package private.  This comment is the same for the methods below which you changed.  Thanks.

**Review by ivakegg — CHANGES_REQUESTED** [review]

File: warehouse/query-core/src/main/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctions.java [hunk 2]
```diff
@@ -1681,7 +1685,7 @@ static boolean betweenInclusive(long value, long left, long right) {
      * @return a {@link ValueTuple}
      * @see ValueTuple#toValueTuple(Object) documentation on conversion details
      */
-    protected static ValueTuple getHitTerm(Object valueTuple) {
+    static ValueTuple getHitTerm(Object valueTuple) {
```
Comment (ivakegg) [inline warehouse/query-core/src/main/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctions.java]: You forgot this one

**Review by ivakegg — CHANGES_REQUESTED** [review]

**Review by ivakegg — DISMISSED** [review]

**Review by apmoriarty — DISMISSED** [review]

**Comment by ivakegg** [comment]
branch pr/1368 updated with latest changes

**Review by ivakegg — APPROVED** [review]
