### PR TITLE
validation - new rule to interpret grouped fielded phrases

### LINKED ISSUE #2874: validation update - unquoted phrases
When searching for an unquoted phrase, it works perfectly if the phrase is immediately after the colon but it is not working if the phrase is in parentheses. For example:

   FIELD:my term -> returns proper error
   FIELD:(my term) -> does not return error

### PR DESCRIPTION
**Pull request by skyler-kv**
`GroupedInterpretationRule` will give a message when a grouped query is something similar to `FOO:(aaa bbb ccc)`, `(FOO:aaa bbb cc)`, or `(FOO:aaa AND FOO:bbb AND FOO:ccc)`

i.e. if the user queries `FOO:(aaa bbb ccc)`, the following message would occur
"Operator precedence may be missing, field(s) `[FOO]` with value(s) `[aaa, bbb, ccc]` will be interpreted as `( FOO:aaa AND FOO:bbb AND FOO:ccc )`"

Fixes #2874

### CODE REVIEW

File: warehouse/query-core/src/main/java/datawave/query/rules/GroupedInterpretationRule.java [hunk 1]
```diff
@@ -0,0 +1,128 @@
...
+
+            String field = (node.toString()).substring(((node.toString()).indexOf("field=\'") + 7), (node.toString()).indexOf("\' text"));
+            if (!field.isEmpty() && !Objects.equals(field, prevField.get(0))) {
+                fieldList.add(field);
+                prevField.set(0, field);
+                fieldValueList[2] = prevField;
+            }
+        }
+
+        return fieldValueList;
```
Comment (foster33) [inline warehouse/query-core/src/main/java/datawave/query/rules/GroupedInterpretationRule.java]: You can probably get rid of this and make the method void. The return value does not seem to be used.

File: warehouse/query-core/src/test/java/datawave/query/rules/ShardQueryRuleTest.java [hunk 2]
```diff
@@ -109,6 +109,7 @@ protected void assertResult() throws Exception {
         rule.setName(ruleName);
 
         ShardQueryValidationConfiguration validationConfiguration = getValidationConfiguration();
+        validationConfiguration.setQueryString(query);
```
Comment (lbschanno) [inline warehouse/query-core/src/test/java/datawave/query/rules/ShardQueryRuleTest.java]: This should be moved to `getValidationConfiguration()`.

File: warehouse/query-core/src/test/java/datawave/query/rules/GroupedInterpretationRuleTest.java [hunk 3]
```diff
@@ -0,0 +1,112 @@
...
+    void testQueryWithGroupedPhraseAndAmbiguousPhrase() throws Exception {
+        givenQuery("FOO:(abc def ghi) FOO:jkl mno");
+
+        expectMessage("Operator precedence may be missing, field(s): [FOO] with value(s): [abc, def, ghi] will be interpreted as: ( FOO:abc AND FOO:def AND FOO:ghi )");
+
+        assertResult();
+    }
+
+    /**
+     * Test a query with ambiguous phrases after a quoted phrase.
```
Comment (lbschanno) [inline warehouse/query-core/src/test/java/datawave/query/rules/GroupedInterpretationRuleTest.java]: Leftover comment from a copy/paste I assume. This should be updated to reflect the actual test scenario or removed.

File: warehouse/query-core/src/test/java/datawave/query/rules/GroupedInterpretationRuleTest.java [hunk 4]
```diff
@@ -0,0 +1,112 @@
...
+    @Test
+    void testGroupedFieldedTerms() throws Exception {
+        givenQuery("(FOO:abc AND BAR:def)");
+
+        // Do not expect any results.
+        assertResult();
+    }
+
+    /**
+     * Test a query with ambiguous phrases before a fielded term.
```
Comment (lbschanno) [inline warehouse/query-core/src/test/java/datawave/query/rules/GroupedInterpretationRuleTest.java]: Same thing as before, this comment should be updated to reflect the actual test scenario or removed.

File: warehouse/query-core/src/test/java/datawave/query/rules/GroupedInterpretationRuleTest.java [hunk 5]
```diff
@@ -0,0 +1,112 @@
...
+    void testMultipleFieldsWithGroupedAmbiguousPhrases() throws Exception {
+        givenQuery("(FOO:abc def ghi) OR BAR:(aaa bbb ccc) AND 333 HAT:\"111\" 222 AND HEN:car VEE:elephant zebra VEE:deer FOO:(aaa bbb)");
+
+        expectMessage("Operator precedence may be missing, field(s): [FOO] with value(s): [abc, def, ghi] will be interpreted as: ( FOO:abc AND def AND ghi )");
+        expectMessage("Operator precedence may be missing, field(s): [BAR] with value(s): [aaa, bbb, ccc] will be interpreted as: ( BAR:aaa AND BAR:bbb AND BAR:ccc )");
+        expectMessage("Operator precedence may be missing, field(s): [FOO] with value(s): [aaa, bbb] will be interpreted as: ( FOO:aaa AND FOO:bbb )");
+
+        assertResult();
+    }
+
```
Comment (lbschanno) [inline warehouse/query-core/src/test/java/datawave/query/rules/GroupedInterpretationRuleTest.java:96]: Tried out the following test cases where a field HAT is located within the grouped terms for the field FOO:

```java
@Test
    void testDifferentFieldGroupedWithinTermGroup() throws Exception {
        givenQuery("FOO:(abc HAT:(def ghi)) OR BAR:(aaa (bbb (ccc)))");
        
        expectMessage("Operator precedence may be missing, field(s): [FOO, HAT] with value(s): [abc, def, ghi] will be interpreted as: ( FOO:abc AND ( HAT:def AND HAT:ghi ) )");
        expectMessage("Operator precedence may be missing, field(s): [BAR] with value(s): [aaa, bbb, ccc] will be interpreted as: ( BAR:aaa AND ( BAR:bbb AND ( BAR:ccc ) ) )");
        
        assertResult();
    }

 @Test
    void testDifferentFieldWithinTermGroup() throws Exception {
        givenQuery("FOO:(abc HAT:def ghi) OR BAR:(aaa (bbb (ccc)))");
        
        expectMessage("Operator precedence may be missing, field(s): [BAR] with value(s): [aaa, bbb, ccc] will be interpreted as: ( BAR:aaa AND ( BAR:bbb AND ( BAR:ccc ) ) )");
        
        assertResult();
    }
```
These scenarios probably don't need to be addressed if you don't really see queries from the customer that look like above.

File: warehouse/query-core/src/main/java/datawave/query/lucene/visitors/GroupedInterpretationVisitor.java [hunk 6]
```diff
@@ -0,0 +1,151 @@
...
+    }
+
+    private boolean junctionConsistsOfUnfieldedTerms(QueryNode node, boolean fieldedTermFound) {
+        List<QueryNode> children = node.getChildren();
+        String prevField = "";
+
+        for (QueryNode child : children) {
+            QueryNodeType type = QueryNodeType.get(child.getClass());
+            if (type == QueryNodeType.FIELD) {
+                if (!((FieldQueryNode) child).getFieldAsString().isEmpty()) {
```
Comment (lbschanno) [inline warehouse/query-core/src/main/java/datawave/query/lucene/visitors/GroupedInterpretationVisitor.java]: You can avoid multiple casts to FieldQueryNode by casting to FieldQueryNode in a local variable, and then referencing the new variable:
```java
FieldQueryNode fieldNode = (FieldQueryNode) child;
if (!fieldNode.getFieldAsString().isEmpty()) {
...
```

File: warehouse/query-core/src/main/java/datawave/query/lucene/visitors/GroupedInterpretationVisitor.java [hunk 7]
```diff
@@ -0,0 +1,151 @@
...
+ * {@code FOO:(aaa bbb ccc)}, {@code (FOO:aaa bbb ccc)}, and {@code (FOO:aaa AND FOO:bbb AND FOO:ccc)}
+ */
+
+public class GroupedInterpretationVisitor extends BaseVisitor {
+
+    public enum JUNCTION {
+        AND(QueryNodeType.AND, AndQueryNode::new), OR(QueryNodeType.OR, OrQueryNode::new);
+
+        private final QueryNodeType type;
+        private final Function<List<QueryNode>,QueryNode> constructor;
```
Comment (lbschanno) [inline warehouse/query-core/src/main/java/datawave/query/lucene/visitors/GroupedInterpretationVisitor.java]: This constructor var is never used and can be removed.

File: warehouse/query-core/src/main/java/datawave/query/lucene/visitors/GroupedInterpretationVisitor.java [hunk 8]
```diff
@@ -0,0 +1,151 @@
...
+    /**
+     * Returns a list of copies of nodes representing fielded terms with unfielded terms directly following them that are conjoined by the specified junction.
+     *
+     * @param node
+     *            the node
+     * @param junction
+     *            the junction type AND/OR
+     * @return the list of ambiguous nodes
+     */
+    public static List<QueryNode> check(QueryNode node, JUNCTION junction) {
```
Comment (lbschanno) [inline warehouse/query-core/src/main/java/datawave/query/lucene/visitors/GroupedInterpretationVisitor.java]: This method is only called once in GroupedInterpretationRule with the argument `JUNCTION.AND`, and I don't see any usage of `JUNCTION.OR`. If we don't need to check OR junctions, then we should simplify this visitor by removing the JUNCTION enum and just overriding the behavior of `visit(AndQueryNode, Object data)`.

File: warehouse/query-core/src/main/java/datawave/query/lucene/visitors/GroupedInterpretationVisitor.java [hunk 9]
```diff
@@ -0,0 +1,151 @@
...
+import org.apache.lucene.queryparser.flexible.core.nodes.GroupQueryNode;
+import org.apache.lucene.queryparser.flexible.core.nodes.OrQueryNode;
+import org.apache.lucene.queryparser.flexible.core.nodes.QueryNode;
+
+/**
+ * A {@link BaseVisitor} implementation that will search a query for any grouped phrases with similar fields, it would identify cases like
+ * {@code FOO:(aaa bbb ccc)}, {@code (FOO:aaa bbb ccc)}, and {@code (FOO:aaa AND FOO:bbb AND FOO:ccc)}
+ */
+
+public class GroupedInterpretationVisitor extends BaseVisitor {
```
Comment (lbschanno) [inline warehouse/query-core/src/main/java/datawave/query/lucene/visitors/GroupedInterpretationVisitor.java:17]: Will you be adding any tests for this class?

File: warehouse/query-core/src/main/java/datawave/query/lucene/visitors/GroupedInterpretationVisitor.java [hunk 10]
```diff
@@ -0,0 +1,151 @@
...
+        } else if (type == junction.getType()) {
+            // examine the children.
+            return junctionConsistsOfUnfieldedTerms(child, fieldedTermFound);
+        } else {
+            // The child is not one of the target types we want
+            return false;
+        }
+    }
+
+    private boolean junctionConsistsOfUnfieldedTerms(QueryNode node, boolean fieldedTermFound) {
```
Comment (lbschanno) [inline warehouse/query-core/src/main/java/datawave/query/lucene/visitors/GroupedInterpretationVisitor.java:93]: This function does not check that the junction consists solely of unfielded terms. This means that you will run into issues when returning messages when a group contains a field with unfielded terms, and some other non-fielded clause, such as the following example:

```java
@Test
void testGroupWithUnfieldedTermsAndNonFieldValueClause() throws Exception {
    givenQuery("(FOO:abc def #ISNOTNULL(HAT))");
        
    expectMessage("Operator precedence may be missing, field(s): [FOO, ion start='13' end='28] with value(s): [abc, def, null] will be interpreted as: ( FOO:abc AND def AND #ISNOTNULL(HAT) )");
        
    assertResult();
}
```
This should return false if any of the children are not field query nodes. See AmbiguousUnfieldedTermsVisitor for some examples.

File: warehouse/query-core/src/main/java/datawave/query/rules/GroupedInterpretationRule.java [hunk 11]
```diff
@@ -0,0 +1,126 @@
...
+        if (prevField.isEmpty()) {
+            prevField.add("");
+        }
+
+        if (!node.toString().isEmpty()) {
+            // adds string values from original query to lists
+            valueList.add((node.toString()).substring(((node.toString()).indexOf("text='") + 6), (node.toString()).indexOf("'/>")));
+
+            String field = (node.toString()).substring(((node.toString()).indexOf("field='") + 7), (node.toString()).indexOf("' text"));
+            if (!field.isEmpty() && !Objects.equals(field, prevField.get(0))) {
```
Comment (lbschanno) [inline warehouse/query-core/src/main/java/datawave/query/rules/GroupedInterpretationRule.java]: It took me a couple of re-reads here to figure out that you were using the prevFields list as a means to get a unique list of field names. We can simplify the formatting code to something like following, utilizing the org.apache.commons.lang3.tuple.Pair class:
```java
    // Return a message about the given nodes.
    private String formatMessage(QueryNode node) {
        System.out.println("formatMessage: " + LuceneQueryStringBuildingVisitor.build(node));
        // @formatter:off
        return new StringBuilder()
                .append("Operator precedence may be missing, ")
                .append(formatGroup((GroupQueryNode) node))
                .append(" will be interpreted as: ")
                .append(LuceneQueryStringBuildingVisitor.build(node))
                .toString();
        // @formatter:on
    }
    
    // Return a formatted string containing the fields and values in the group.
    private String formatGroup(GroupQueryNode node) {
        Pair<Set<String>,List<String>> fieldValues = Pair.of(new HashSet<>(), new ArrayList<>());
        collectFieldsAndValues(node, fieldValues);
        return  "field(s): " + fieldValues.getLeft() + " with value(s): " + fieldValues.getRight();
    }
    
    // Collect the fields and values in the given node, traveling down through the children.
    private void collectFieldsAndValues(QueryNode node, Pair<Set<String>, List<String>> fieldValues) {
        for(QueryNode child : node.getChildren()) {
            QueryNodeType childType = QueryNodeType.get(child.getClass());
            switch (childType) {
                case GROUP:
                case OR:
                case AND:
                    collectFieldsAndValues(child, fieldValues);
                    return;
                default:
                    // Skip any non-field query nodes.
                    if(child instanceof FieldQueryNode) {
                        FieldQueryNode fqn = (FieldQueryNode) child;
                        String field = fqn.getField().toString();
                        if (!field.isEmpty()) {
                            fieldValues.getLeft().add(field);
                        }
                        fieldValues.getRight().add(fqn.getTextAsString());
                    }
            }
        }
    }

```

**Review by lbschanno — CHANGES_REQUESTED** [review]

File: warehouse/query-core/src/main/java/datawave/query/rules/GroupedInterpretationRule.java (hunk 11 above)
Comment (lbschanno) [reply warehouse/query-core/src/main/java/datawave/query/rules/GroupedInterpretationRule.java]: Note: the proposed changes here would help avoid the formatting issues noted in [this comment](https://github.com/NationalSecurityAgency/datawave/pull/3088#discussion_r2261087274). With these changes, that test case shows the following:
```java
@Test
void testGroupWithUnfieldedTermsAndNonFieldValueClause() throws Exception {
    givenQuery("(FOO:abc def #ISNOTNULL(HAT))");
    
    expectMessage("Operator precedence may be missing, field(s): [FOO] with value(s): [abc, def] will be interpreted as: ( FOO:abc AND def AND #ISNOTNULL(HAT) )");
    
    assertResult();
}
```

File: warehouse/query-core/src/main/java/datawave/query/lucene/visitors/GroupedInterpretationVisitor.java [hunk 12]
```diff
@@ -0,0 +1,128 @@
...
+    /**
+     * Returns a list of copies of nodes representing fielded terms with unfielded terms directly following them that are conjoined by the specified junction.
+     *
+     * @param node
+     *            the node
+     * @param junction
+     *            the junction type AND
+     * @return the list of ambiguous nodes
+     */
+    public static List<QueryNode> check(QueryNode node, QueryNodeType junction) {
```
Comment (lbschanno) [inline warehouse/query-core/src/main/java/datawave/query/lucene/visitors/GroupedInterpretationVisitor.java]: This function is only ever called with `QueryNodeType.AND`. Can we simply remove the junction parameter here and default to calling `checkJunction` in `visit(AndQueryNode node, Object data)`?

File: warehouse/query-core/src/test/java/datawave/query/lucene/visitors/GroupedInterpretationVisitorTest.java [hunk 13]
```diff
@@ -0,0 +1,254 @@
...
+import datawave.query.language.parser.lucene.AccumuloSyntaxParser;
+import datawave.query.language.parser.lucene.EscapeQuerySyntaxImpl;
+
+class GroupedInterpretationVisitorTest {
+
+    private static final SyntaxParser parser = new AccumuloSyntaxParser();
+    private static final EscapeQuerySyntax escapedSyntax = new EscapeQuerySyntaxImpl();
+
+    private String query;
+    private String junction;
```
Comment (lbschanno) [inline warehouse/query-core/src/test/java/datawave/query/lucene/visitors/GroupedInterpretationVisitorTest.java]: The junction field here is never used. This can be deleted.

File: warehouse/query-core/src/test/java/datawave/query/lucene/visitors/GroupedInterpretationVisitorTest.java [hunk 14]
```diff
@@ -0,0 +1,254 @@
...
+    void tearDown() {
+        query = null;
+        junction = null;
+        expectedNodes.clear();
+    }
+
+    /**
+     * Test a query with a single fielded term.
+     */
+    @ParameterizedTest
```
Comment (lbschanno) [inline warehouse/query-core/src/test/java/datawave/query/lucene/visitors/GroupedInterpretationVisitorTest.java]: The `@ParameterizedTest` annotations are not needed for these tests since we only ever pass in the AND junction. All occurrences of 
```java
@ParameterizedTest
@ValueSource(strings = {"AND"})
void testName(String junction) {
```
can be replaced with
```java
@Test
void testName() {
```

File: warehouse/query-core/src/main/java/datawave/query/rules/GroupedInterpretationRule.java [hunk 15]
```diff
@@ -0,0 +1,104 @@
...
+    }
+
+    @Override
+    public QueryRule copy() {
+        return new GroupedInterpretationRule(name);
+    }
+
+    // Return a message about the given nodes.
+    private String formatMessage(QueryNode node) {
+        System.out.println("formatMessage: " + LuceneQueryStringBuildingVisitor.build(node));
```
Comment (lbschanno) [inline warehouse/query-core/src/main/java/datawave/query/rules/GroupedInterpretationRule.java]: This system.out should be deleted.

File: warehouse/query-core/src/test/java/datawave/query/lucene/visitors/GroupedInterpretationVisitorTest.java [hunk 16]
```diff
@@ -0,0 +1,254 @@
...
+import org.apache.lucene.queryparser.flexible.core.parser.SyntaxParser;
+import org.junit.jupiter.api.AfterEach;
+import org.junit.jupiter.api.Assertions;
+import org.junit.jupiter.params.ParameterizedTest;
+import org.junit.jupiter.params.provider.ValueSource;
+
+import datawave.query.language.parser.lucene.AccumuloSyntaxParser;
+import datawave.query.language.parser.lucene.EscapeQuerySyntaxImpl;
+
+class GroupedInterpretationVisitorTest {
```
Comment (lbschanno) [inline warehouse/query-core/src/test/java/datawave/query/lucene/visitors/GroupedInterpretationVisitorTest.java:18]: I noticed that there is no test case covering the case where you have unfielded terms inside a group along with a non-fielded clause, such as the following:

```java
@Test
void testGroupedUnfieldedTermWithNonFieldedClause() throws QueryNodeParseException {
    givenQuery("(FOO:abc def #ISNOTNULL(HAT))");
    
    expectNode("(FOO:abc def #ISNOTNULL(HAT))");
    
    assertResult();
}
```
I would add a test like this to this test suite, and make sure that you are getting the result you want.

**Review by lbschanno — CHANGES_REQUESTED** [review]

File: warehouse/query-core/src/main/java/datawave/query/lucene/visitors/GroupedInterpretationVisitor.java [hunk 17]
```diff
@@ -0,0 +1,125 @@
...
+     *            the node
+     * @return the list of ambiguous nodes
+     */
+    public static List<QueryNode> check(QueryNode node) {
+        GroupedInterpretationVisitor visitor = new GroupedInterpretationVisitor(QueryNodeType.AND);
+        // noinspection unchecked
+        return (List<QueryNode>) visitor.visit(node, new ArrayList<QueryNode>());
+    }
+
+    private final QueryNodeType junction;
```
Comment (lbschanno) [inline warehouse/query-core/src/main/java/datawave/query/lucene/visitors/GroupedInterpretationVisitor.java]: `junction` is always an instance of `QueryNodeType.AND`. We can delete `junction` and remove the check against junction in `visit(AndQueryNode node, Object data)`, and simply call `checkJunction()` there.

**Review by lbschanno — CHANGES_REQUESTED** [review]

**Review by lbschanno — APPROVED** [review]

**Review by apmoriarty — APPROVED** [review]
