### PR TITLE
fixes #163 - Updated Intersection constructor to mark a node as ABSEN…

### LINKED ISSUE #163: RangeStream fails to create Intersection for EXCEEDED_VALUE_THRESHOLD nodes when querying outside the date range cap
Either update the date range cap to always fail if we are outside the valid range, or update the Intersection logic to handle this properly.

### PR DESCRIPTION
**Pull request by jwomeara**
…T if it contains an EXCEEDED_VALUE_THRESHOLD IndexStream with no ranges to scan.

### CODE REVIEW

File: warehouse/query-core/src/main/java/datawave/query/index/lookup/Intersection.java [hunk 1]
```diff
@@ -70,8 +70,6 @@ public Intersection(Iterable<? extends IndexStream> children, UidIntersector uid
         isVariable = false;
         if (childrenItr.hasNext()) {
             boolean absent = false;
-            boolean exceededTermThreshold = false;
```
Comment (jwomeara) [inline warehouse/query-core/src/main/java/datawave/query/index/lookup/Intersection.java]: These fields were unused, so I removed them.

File: warehouse/query-core/src/main/java/datawave/query/index/lookup/Intersection.java [hunk 2]
```diff
@@ -83,9 +81,6 @@ public Intersection(Iterable<? extends IndexStream> children, UidIntersector uid
                     continue;
                 
                 if (stream.hasNext()) {
-                    if (StreamContext.EXCEEDED_VALUE_THRESHOLD == stream.context()) {
```
Comment (jwomeara) [inline warehouse/query-core/src/main/java/datawave/query/index/lookup/Intersection.java]: This was essentially a noop, so I removed it.

File: warehouse/query-core/src/main/java/datawave/query/index/lookup/RangeStream.java [hunk 3]
```diff
@@ -871,12 +871,6 @@ public static boolean isNormalized(String field, Set<String> ctx) {
         Calendar end = Calendar.getInstance();
         end.setTime(config.getEndDate());
         
-        List<String> datatypes = new ArrayList<>();
```
Comment (jwomeara) [inline warehouse/query-core/src/main/java/datawave/query/index/lookup/RangeStream.java]: This wasn't being used for anything, so I removed it.
