### PR TITLE
fixes #596 SourceManager properly manages more sources than initialSize

### LINKED ISSUE #596: SourceManager incorrectly manages sources
When a SourceManager re-uses a source (createdSize >= initialSize) the SourceManager incorrectly manages the underlying sources.

### PR DESCRIPTION
**Pull request by FineAndDandy**

### CODE REVIEW

File: warehouse/query-core/src/test/java/datawave/query/iterator/SortedListKeyValueIterator.java [hunk 1]
```diff
@@ -38,6 +39,14 @@ public SortedListKeyValueIterator(List<Map.Entry<Key,Value>> sourceList) {
         currentIndex = 0;
     }
     
+    public SortedListKeyValueIterator(SortedMap<Key,Value> map) {
+        this.sourceList = new ArrayList<>(map.entrySet().size());
+        currentIndex = 0;
+        for (Map.Entry<Key,Value> entry : map.entrySet()) {
+            sourceList.add(entry);
+        }
```
Comment (apmoriarty) [inline warehouse/query-core/src/test/java/datawave/query/iterator/SortedListKeyValueIterator.java]: Could this be a sourceList.addAll(map.entrySet())?
Does the currentIndex indicate another possible constructor where we preserve the current index?

File: warehouse/query-core/src/test/java/datawave/query/iterator/SourceManagerTest.java [hunk 2]
```diff
@@ -51,6 +55,112 @@ public void setup() throws ParseException, IOException {
...
+            copy1.next();
+            copy2.next();
+        }
+        
+        assertFalse(copy1.hasTop());
+        assertFalse(copy2.hasTop());
+        assertEquals(copy1Count, alternatingCount);
+        
+        // different ranges
+        copy1.seek(new Range(new Key("20121126_2"), true, new Key("20121126_3"), false), Collections.emptyList(), false);
```
Comment (apmoriarty) [inline warehouse/query-core/src/test/java/datawave/query/iterator/SourceManagerTest.java]: I would prefer to see this test broken out into the cases of "same range" - "different range". If a future change would only break one behavior it will be obvious up front which behavior is broken.

File: warehouse/query-core/src/main/java/datawave/query/iterator/SourceManager.java [hunk 3]
```diff
@@ -178,8 +210,16 @@ public void seek(Range range, Collection<ByteSequence> columnFamilies, boolean i
             
             try {
                 lastKey = child.getTopKey();
+                lastValue = child.getTopValue();
+                rangeDone = false;
```
Comment (ivakegg) [inline warehouse/query-core/src/main/java/datawave/query/iterator/SourceManager.java]: Lets move the setting of rangeDone to false to the top of the method.  This will allow us to remove a mess of sets below and guarentee we did not forget to set it on some path therein.

Comment (ivakegg) [reply warehouse/query-core/src/main/java/datawave/query/iterator/SourceManager.java]: Perhaps setting the lastKey and lastValue to null at the top would also be good

File: warehouse/query-core/src/main/java/datawave/query/iterator/SourceManager.java [hunk 4]
```diff
@@ -105,40 +132,48 @@ public void init(SortedKeyValueIterator<Key,Value> source, Map<String,String> op
...
             
             child.next();
             
             try {
                 lastKey = child.getTopKey();
+                lastValue = child.getTopValue();
+                
+                // need to understand when to expect no more keys for this range to differentiate from the start case
+                if (lastKey == null) {
+                    rangeDone = true;
```
Comment (ivakegg) [inline warehouse/query-core/src/main/java/datawave/query/iterator/SourceManager.java]: set lastValue to null here or move the child.getTopValue() into and else clause

File: warehouse/query-core/src/main/java/datawave/query/iterator/SourceManager.java [hunk 5]
```diff
@@ -178,8 +210,16 @@ public void seek(Range range, Collection<ByteSequence> columnFamilies, boolean i
             
             try {
                 lastKey = child.getTopKey();
+                lastValue = child.getTopValue();
+                rangeDone = false;
+                
+                if (lastKey == null) {
+                    rangeDone = true;
+                }
             } catch (Exception e) {
```
Comment (ivakegg) [inline warehouse/query-core/src/main/java/datawave/query/iterator/SourceManager.java]: no need to catch exception....in fact this is wrong (good catch @FineAndDandy )

File: warehouse/query-core/src/main/java/datawave/query/iterator/SourceManager.java (hunk 4 above)
Comment (FineAndDandy) [reply warehouse/query-core/src/main/java/datawave/query/iterator/SourceManager.java]: lastValue should be set to null already if lastKey is set to null

**Comment by FineAndDandy** [comment]
there is also no reason hasTop() shouldn't just check the lastKey != null. This may save on some reseeking

File: warehouse/query-core/src/test/java/datawave/query/iterator/SourceManagerTest.java (hunk 2 above)
Comment (FineAndDandy) [reply warehouse/query-core/src/test/java/datawave/query/iterator/SourceManagerTest.java]: done
