### PR TITLE
fixes #892: ExecutableDeterminationVisitor properly handles empty states

### LINKED ISSUE #892: ExecutableDeterminationVisitor incorrectly evaluates empty Reference/ReferenceExpression nodes
allOrSome() and allOrNone() both assume there is at least one state when processing. They need to test for no states and should return IGNORABLE under this condition.

### PR DESCRIPTION
**Pull request by FineAndDandy**

### CODE REVIEW

**Comment by FineAndDandy** [comment]
I am adding a unit test quick

File: warehouse/query-core/src/test/java/datawave/query/jexl/visitors/ExecutableDeterminationVisitorTest.java [hunk 1]
```diff
@@ -413,4 +421,143 @@ public void testNegationEvaluation() {
...
+        
+        HashSet indexedFields = new HashSet();
+        indexedFields.add("INDEXONLYFIELD");
+        indexedFields.add("INDEXEDFIELD");
+        
+        HashSet<String> indexOnlyFields = new HashSet<>();
+        indexOnlyFields.add("INDEXONLYFIELD");
+        
+        EasyMock.expect(config.getIndexedFields()).andReturn(indexedFields).anyTimes();
+        EasyMock.expect(helper.getIndexOnlyFields(null)).andReturn(indexOnlyFields).anyTimes();
```
Comment (jwomeara) [inline warehouse/query-core/src/test/java/datawave/query/jexl/visitors/ExecutableDeterminationVisitorTest.java:464]: Ew...  easymock...
